/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-26 02:33:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class usermypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function checkUsrSubmit() {\r\n");
      out.write("		var ID = $('#saveForm #USR_NM');\r\n");
      out.write("		var PW = $('#saveForm #ENPWD');\r\n");
      out.write("		if (!ID.val()) {\r\n");
      out.write("			alert('ID를 입력하세요.');\r\n");
      out.write("			ID.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		if (!PW.val()) {\r\n");
      out.write("			alert('비밀번호를 입력하세요.');\r\n");
      out.write("			PW.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function () {\r\n");
      out.write("		var type = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.phone1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("		var type2 = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.email2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("		$(\"#user_phone\").val(type).attr(\"selected\",\"selected\");\r\n");
      out.write("		$(\"#select_target_3\").val(type2).attr(\"selected\",\"selected\");\r\n");
      out.write("		$(\"#USR_EMADR_2\").val(type2);\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	function unsign(){\r\n");
      out.write("		var check = confirm(\"정말 탈퇴 하시겠습니까?\");\r\n");
      out.write("		if(check){\r\n");
      out.write("			return location.href='/ongo/member/unsign?member_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		}else{\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- content -->\r\n");
      out.write("	<div id=\"contents\">\r\n");
      out.write("		<!-- title -->\r\n");
      out.write("		<div class=\"sub_top\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<h1>마이페이지</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- //title -->\r\n");
      out.write("\r\n");
      out.write("		<!-- 게시판 -->\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("		<!-- 히든 : 화면에는 보이지 않는데 넘겨준다 -->\r\n");
      out.write("			<form action=\"/ongo/member/usermypage?member_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"POST\">\r\n");
      out.write("				<div class=\"cont-box-inner\">\r\n");
      out.write("					<div class=\"title\">\r\n");
      out.write("						<h3 class=\"h4\">정보수정</h3>\r\n");
      out.write("						<p class=\"highlight org-txt\">* 필수입력사항</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"tbl grid-layout grid2\">\r\n");
      out.write("						<div class=\"grid-item\">\r\n");
      out.write("							<label for=\"USR_NM\">성명<em class=\"org-txt asterisk\"\r\n");
      out.write("								title=\"필수\">*</em></label>\r\n");
      out.write("							<div class=\"tbl-basic-td\">\r\n");
      out.write("								<div class=\"input-wrap\">\r\n");
      out.write("									<input class=\"grid-input\" type=\"text\" name=\"member_name\"\r\n");
      out.write("										title=\"이름\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("										<input type=\"hidden\" class=\"grid-input\" type=\"text\" name=\"member_name\"\r\n");
      out.write("										title=\"이름\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"grid-item\">\r\n");
      out.write("							<label for=\"USR_MBTN\">휴대전화번호<em class=\"org-txt asterisk\"\r\n");
      out.write("								title=\"필수\">*</em></label> <input type=\"hidden\" name=\"USR_MBTN\">\r\n");
      out.write("							<div class=\"tbl-basic-td\">\r\n");
      out.write("								<div class=\"input-wrap w30\">\r\n");
      out.write("									<select class=\"form-select grid-input\" id=\"user_phone\"\r\n");
      out.write("										name=\"phone1\" data-col=\"USR_MBTN_1\" title=\"휴대전화번호\">\r\n");
      out.write("										<option value=\"\">선택</option>\r\n");
      out.write("										<option value=\"010\">010</option>\r\n");
      out.write("										<option value=\"011\">011</option>\r\n");
      out.write("										<option value=\"016\">016</option>\r\n");
      out.write("										<option value=\"017\">017</option>\r\n");
      out.write("										<option value=\"018\">018</option>\r\n");
      out.write("										<option value=\"019\">019</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</div>\r\n");
      out.write("								-\r\n");
      out.write("								<div class=\"input-wrap w30\">\r\n");
      out.write("									<input class=\"grid-input\" type=\"text\" name=\"phone2\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.phone2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=\"4\" pattern=\"[0-9]+\"\r\n");
      out.write("										title=\"휴대전화번호 앞자리 입력\">\r\n");
      out.write("								</div>\r\n");
      out.write("								-\r\n");
      out.write("								<div class=\"input-wrap w30\">\r\n");
      out.write("									<input class=\"grid-input\" type=\"text\" name=\"phone3\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.phone3}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxlength=\"4\" pattern=\"[0-9]+\"\r\n");
      out.write("										title=\"휴대전화번호 뒷자리 입력\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"grid-item colspan2\">\r\n");
      out.write("							<label for=\"HOFS_ADDR\">아이디<em class=\"org-txt asterisk\"\r\n");
      out.write("								title=\"필수\">*</em></label>\r\n");
      out.write("							<div class=\"tbl-basic-td\">\r\n");
      out.write("								<div class=\"input-wrap\">\r\n");
      out.write("									<input class=\"grid-input\" type=\"text\" role=\"textbox\"\r\n");
      out.write("										id=\"USER_ID\" name=\"member_id\" maxlength=\"12\" title=\"아이디 입력\"\r\n");
      out.write("										value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"grid-item colspan2\">\r\n");
      out.write("							<label for=\"ENPWD\">비밀번호<em class=\"org-txt asterisk\"\r\n");
      out.write("								title=\"필수\">*</em></label>\r\n");
      out.write("							<div class=\"tbl-basic-td\">\r\n");
      out.write("								<div class=\"input-wrap\">\r\n");
      out.write("									<input class=\"grid-input\" type=\"password\" role=\"textbox\"\r\n");
      out.write("										id=\"ENPWD\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.member_pw}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"ENPWD\"\r\n");
      out.write("										name=\"member_pw\" maxlength=\"20\" title=\"비밀번호 입력\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<span>(4자리 이상, 20자리 이하)<span></span>\r\n");
      out.write("								</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"grid-item colspan2\">\r\n");
      out.write("							<label for=\"ENPWD2\">비밀번호확인<em class=\"org-txt asterisk\"\r\n");
      out.write("								title=\"필수\">*</em></label>\r\n");
      out.write("							<div class=\"tbl-basic-td\">\r\n");
      out.write("								<div class=\"input-wrap\">\r\n");
      out.write("									<input class=\"grid-input\" type=\"password\" role=\"textbox\"\r\n");
      out.write("										id=\"ENPWD2\" name=\"member_pw2\" maxlength=\"20\" title=\"비밀번호확인 입력\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<span>비밀번호 확인을 위해 한번 더 입력해 주세요.</span>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"grid-item colspan2\">\r\n");
      out.write("							<label for=\"HOFS_ADDR\">주소</label>\r\n");
      out.write("							<div class=\"tbl-basic-td\">\r\n");
      out.write("								<div class=\"input-wrap w10\">\r\n");
      out.write("									<input value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.zipcode}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"grid-input\" type=\"text\"\r\n");
      out.write("										name=\"zipcode\" title=\"우편번호\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<button type=\"button\" class=\"btn btn-light\"\r\n");
      out.write("									onclick=\"execDaumPostcode()\">우편번호 검색</button>\r\n");
      out.write("								<div class=\"input-wrap\">\r\n");
      out.write("\r\n");
      out.write("									<br>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"\">\r\n");
      out.write("									<div class=\"input-wrap \">\r\n");
      out.write("										<input class=\"grid-input\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.member_addr1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("											type=\"text\" name=\"member_addr1\" title=\"주소\">\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"input-wrap\">\r\n");
      out.write("										<input class=\"grid-input\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.member_addr2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("											type=\"text\" name=\"member_addr2\" placeholder=\"상세주소를 입력해주세요.\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<div class=\"grid-item colspan2\">\r\n");
      out.write("							<label for=\"USR_EMADR\">이메일주소<em class=\"org-txt asterisk\"\r\n");
      out.write("								title=\"필수\">*</em></label> <input type=\"hidden\" id=\"USR_EMADR\"\r\n");
      out.write("								name=\"USR_EMADR\">\r\n");
      out.write("							<div class=\"tbl-basic-td\">\r\n");
      out.write("								<div class=\"input-wrap\">\r\n");
      out.write("									<!-- e-아이디, e-도메인, e-도메인유저인풋 \r\n");
      out.write("									<div>test</div>\r\n");
      out.write("									<div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>-->\r\n");
      out.write("\r\n");
      out.write("									<input class=\"grid-input\" type=\"text\" role=\"textbox\"\r\n");
      out.write("										id=\"USR_EMADR_1\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.email1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"email1\"\r\n");
      out.write("										maxlength=\"10\" title=\"이메일주소 입력\">\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"input-wrap\">\r\n");
      out.write("									<input class=\"grid-input\" type=\"text\" role=\"textbox\"\r\n");
      out.write("										id=\"USR_EMADR_2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userMode.email99}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"email99\"\r\n");
      out.write("										title=\"이메일주소 입력\" disabled>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"input-wrap w20\">\r\n");
      out.write("									<select class=\"form-select grid-input\" id=\"select_target_3\"\r\n");
      out.write("										name=\"email2\" data-col=\"\" title=\"이메일\">\r\n");
      out.write("										<option value=\"\" selected>이메일선택</option>\r\n");
      out.write("										<option value=\"naver.com\">naver.com</option>\r\n");
      out.write("										<option value=\"hanmail.net\">hanmail.net</option>\r\n");
      out.write("										<option value=\"gmail.com\">gmail.com</option>\r\n");
      out.write("										<option value=\"nate.com\">nate.com</option>\r\n");
      out.write("										<option value=\"directly\">직접입력하기</option>\r\n");
      out.write("									</select>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"btn-area\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-outline-secondary btn-large\"\r\n");
      out.write("						title=\"회원탈퇴\" onclick=\"return unsign()\">회원탈퇴</button>\r\n");
      out.write("					<button class=\"btn btn-outline-primary btn-large\" type=\"submit\">수정</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- // 게시판 -->\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //contents -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer -->\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- //Footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
