/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-26 02:04:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.history;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dealsellList_005fver4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/DevelUp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DevelUp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/DevelUp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DevelUp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1671969684817L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\n");
      out.write("	href=\"/ongo/common/css/dealhistory.css\">\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	mystate = \"\";\n");
      out.write("	/* 1. 거래상태별 게시글 조회  */\n");
      out.write("	var type = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product_state}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("	console.log(mystate)\n");
      out.write("	var trobj;\n");
      out.write("	$(document)\n");
      out.write("			.ready(\n");
      out.write("					function() {\n");
      out.write("						$(\"#product_state\").val(type).attr(\"selected\",\n");
      out.write("								\"selected\");\n");
      out.write("						$(\"#product_state\")\n");
      out.write("								.change(\n");
      out.write("										function() {\n");
      out.write("\n");
      out.write("											location.href = \"/ongo/history/dealsellList?member_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&product_state=\"\n");
      out.write("													+ encodeURI($(this).val());\n");
      out.write("										})\n");
      out.write("\n");
      out.write("						/* 2. 판매중 list > 거래요청한 유저 정보보기 - ajax로 통신  */\n");
      out.write("						$(\".showReqID\")\n");
      out.write("								.on(\n");
      out.write("										\"click\",\n");
      out.write("										function() {\n");
      out.write("											trobj = $(this).closest(\"tr\")\n");
      out.write("													.next()\n");
      out.write("\n");
      out.write("											//버튼과 가장 가까운 tr 태그의 다음 tr 태그를 선택 \n");
      out.write("											// => 버튼 클릭할 때마다 거래요청id tr 이 보이거나 닫힘  \n");
      out.write("											reqtr = $(this).closest(\"tr\")\n");
      out.write("													.next()\n");
      out.write("											//	= 거래요청 tr  \n");
      out.write("											num = reqtr.attr(\"id\")\n");
      out.write("											//	= 거래요청 tr의 id의 속성 값 = 게시글 번호 \n");
      out.write("											datanode = $(reqtr).children()\n");
      out.write("													.find(\".reqdata\")\n");
      out.write("											// 거래요청 tr의 자식 노드 중 reqdate 라는 클래스명을 가진 자식노드 찾음 \n");
      out.write("											// = ajax를 통해 가져올 데이터가 출력될 부분  \n");
      out.write("											// $(datanode).html(num+\"<span>번 게시글/////</span>\") \n");
      out.write("											//ajax요청결과를 datanode에 출력하기\n");
      out.write("\n");
      out.write("											state = $(this).closest(\"tr\");\n");
      out.write("											mystate = state.attr(\"id\");\n");
      out.write("\n");
      out.write("											$\n");
      out.write("													.ajax({\n");
      out.write("														url : \"/ongo/history/dealReqinfo\",\n");
      out.write("														type : \"get\",\n");
      out.write("														data : {\n");
      out.write("															\"deal_number\" : num\n");
      out.write("														},\n");
      out.write("														success : function(data) {\n");
      out.write("\n");
      out.write("															if (data.length != 0) {\n");
      out.write("																trobj.toggle()\n");
      out.write("\n");
      out.write("																$(\".reqdata\")\n");
      out.write("																		.empty();\n");
      out.write("																/* 3. 구매요청 list > 구매요청한 유저 정보 출력   */\n");
      out.write("																for (i = 0; i < data.length; i++) {\n");
      out.write("\n");
      out.write("																	/* (1) 거래상태가 '거래진행중'일 경우 */\n");
      out.write("																	if (mystate == '거래진행중') {\n");
      out.write("\n");
      out.write("																		/* (1) - 1 ) 구매요청한 사람 = 구매자인 경우 */\n");
      out.write("																		if (data[i].req_id == data[i].buyer_id) {\n");
      out.write("\n");
      out.write("																			dealreqinfo = \"\";\n");
      out.write("\n");
      out.write("																			var dealcancle = \"/ongo//history/dealcancle?&deal_number=\"\n");
      out.write("																					+ data[i].deal_number\n");
      out.write("\n");
      out.write("																			dealreqinfo = \"<tr ><td id='no'>\"\n");
      out.write("																					+ data[i].deal_number\n");
      out.write("																					+ \"</td><td id='date'>\"\n");
      out.write("																					+ data[i].req_time\n");
      out.write("																					+ \"</td><td id='id'>\"\n");
      out.write("																					+ data[i].req_id\n");
      out.write("																					+ \"</td><td id='deal-btn'><a class='dealcancle' href='\"+dealcancle+\"'><button type='button' class='btn btn-warning'\"\n");
      out.write("																					+ \">거래취소</button></a></td></tr>\"\n");
      out.write("\n");
      out.write("																			$(\".dealcancle\").on(\"click\",function() {\n");
      out.write("																				alert(\"거래가 취소되었습니다.\")})\n");
      out.write("\n");
      out.write("																			/* (1) - 2 ) 구매요청한 사람 =/= 구매자인 경우 */\n");
      out.write("																		} else {\n");
      out.write("\n");
      out.write("																			dealreqinfo = \"\";\n");
      out.write("\n");
      out.write("																			dealreqinfo = \"<tr ><td id='no'>\"\n");
      out.write("																					+ data[i].deal_number\n");
      out.write("																					+ \"</td><td id='date'>\"\n");
      out.write("																					+ data[i].req_time\n");
      out.write("																					+ \"</td><td id='id'>\"\n");
      out.write("																					+ data[i].req_id\n");
      out.write("																					+ \"</td><td id='deal-btn'><button type='button' class='btn btn-outline-secondary'\"\n");
      out.write("																					+\">선택불가</button></td></tr>\"\n");
      out.write("\n");
      out.write("																		}\n");
      out.write("\n");
      out.write("																		/* (2) 거래상태가 '판매중'일 경우 */\n");
      out.write("																	} else if (mystate == '판매중') {\n");
      out.write("\n");
      out.write("																		dealreqinfo = \"\";\n");
      out.write("\n");
      out.write("																		var url_string = \"/ongo/history/choicebuyer?dealreq_no=\"\n");
      out.write("																				+ data[i].dealreq_no\n");
      out.write("																				+ \"&req_id=\"\n");
      out.write("																				+ data[i].req_id\n");
      out.write("																				+ \"&deal_number=\"\n");
      out.write("																				+ data[i].deal_number\n");
      out.write("																				+ \"&member_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("\n");
      out.write("																		dealreqinfo = \"<tr ><td id='no'>\"\n");
      out.write("																				+ data[i].deal_number\n");
      out.write("																				+ \"</td><td id='date'>\"\n");
      out.write("																				+ data[i].req_time\n");
      out.write("																				+ \"</td><td id='id'>\"\n");
      out.write("																				+ data[i].req_id\n");
      out.write("																				+ \"</td><td id='deal-btn'><a href='\"+ url_string +\"'><button type='button' class='btn btn-info dealbtn text-white'\"\n");
      out.write("																				+ \">거래하기</button></a></td></tr>\"\n");
      out.write("\n");
      out.write("																		/* (3) 거래상태가 '판매종료'일 경우 */\n");
      out.write("																	} else {\n");
      out.write("\n");
      out.write("																		dealreqinfo = \"\";\n");
      out.write("\n");
      out.write("																		dealreqinfo = \"<tr ><td></td><td></td><td rowspan='2'><span>거래가 완료된 게시물입니다.</span></td></tr>\"\n");
      out.write("\n");
      out.write("																	}\n");
      out.write("\n");
      out.write("																	$(\".reqdata\").append(\n");
      out.write("																		dealreqinfo);\n");
      out.write("																} //for문 end\n");
      out.write("\n");
      out.write("															} else { //=(data.length == 0)  \n");
      out.write("																alert(\"거래요청 내역이 존재하지 않습니다.\")\n");
      out.write("\n");
      out.write("															} // 제일 바깥 if문 end\n");
      out.write("\n");
      out.write("														},//success의 end\n");
      out.write("														error : function(a, b,\n");
      out.write("																c) {\n");
      out.write("															alert(\"오류발생\" + a\n");
      out.write("																	+ b + c)\n");
      out.write("														} //end error			\n");
      out.write("													}) //end ajax					\n");
      out.write("										}) //end click\n");
      out.write("\n");
      out.write("					}) //end ready\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- content -->\n");
      out.write("	<div id=\"contents\">\n");
      out.write("		<!-- title -->\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"sub_top\">\n");
      out.write("				<h1>판매관리</h1>\n");
      out.write("				<span> 내가 게시한 판매글을 조회할 수 있습니다.</span>\n");
      out.write("			</div>\n");
      out.write("			<!-- //title -->\n");
      out.write("\n");
      out.write("			<!-- 조회 테이블 시작 -->\n");
      out.write("			<div class=\"tableDefault table-vertical mb-5 mt-5\">\n");
      out.write("				<table class=\"filter-tb\">\n");
      out.write("					<tbody>\n");
      out.write("						<tr>\n");
      out.write("							<th>게시글 조회</th>\n");
      out.write("							<td>\n");
      out.write("								<div class=\"form-inline\">\n");
      out.write("									<div class=\"select \">\n");
      out.write("										<select class=\"form-select\" id=\"product_state\"\n");
      out.write("											name=\"product_state\" title=\"거래상태 조회\">\n");
      out.write("											<option value=\"all\">전체</option>\n");
      out.write("											<option value=\"판매중\">판매중</option>\n");
      out.write("											<option value=\"거래진행중\">거래진행중</option>\n");
      out.write("											<option value=\"판매완료\">판매완료</option>\n");
      out.write("										</select>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						<!-- 	<tr>\n");
      out.write("							<th rowspan=\"2\">기간별<br class=\"visible-xs\"> 조회\n");
      out.write("							</th>\n");
      out.write("						</tr>\n");
      out.write("						<tr>\n");
      out.write("							<td>\n");
      out.write("								<div class=\"visible-lg visible-md\">\n");
      out.write("									<label class=\"radio-inline\"> <input type=\"radio\"\n");
      out.write("										name=\"type_radio\" value=\"all\" checked=\"\"> 전체보기\n");
      out.write("									</label> <label class=\"radio-inline\"> <input type=\"radio\"\n");
      out.write("										name=\"type_radio\" value=\"month\"> 월별보기\n");
      out.write("									</label> <label class=\"radio-inline\"> <input type=\"radio\"\n");
      out.write("										name=\"type_radio\" value=\"range-7d\"> 최근일주일\n");
      out.write("									</label> <label class=\"radio-inline\"> <input type=\"radio\"\n");
      out.write("										name=\"type_radio\" value=\"range-1m\"> 최근1개월\n");
      out.write("									</label> <label class=\"radio-inline\"> <input type=\"radio\"\n");
      out.write("										name=\"type_radio\" value=\"range-3m\"> 최근3개월\n");
      out.write("									</label>\n");
      out.write("								</div>\n");
      out.write("							</td>\n");
      out.write("						</tr>\n");
      out.write("						\n");
      out.write("						<tr>\n");
      out.write("							<th>키워드 검색</th>\n");
      out.write("							<td>\n");
      out.write("								<div class=\"form-inline\">\n");
      out.write("									<div class=\"form-group\">\n");
      out.write("										<select name=\"field\" id=\"field\" class=\"form-control dpInblock\">\n");
      out.write("											<option value=\"SG\" selected=\"\">통합검색</option>\n");
      out.write("											<option value=\"SA\">물품번호</option>\n");
      out.write("											<option value=\"SB\">물품제목</option>\n");
      out.write("											<option value=\"SC\">구매요청ID</option>\n");
      out.write("											<option value=\"SH\">물품내용</option>\n");
      out.write("										</select>\n");
      out.write("									</div>\n");
      out.write("									<p class=\"visible-xs mb5\"></p>\n");
      out.write("									<div class=\"form-group\">\n");
      out.write("										<input type=\"text\" class=\"form-control inputSearchText\"\n");
      out.write("											name=\"qry\" id=\"qry\" value=\"\">\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</td>\n");
      out.write("						</tr> -->\n");
      out.write("					</tbody>\n");
      out.write("				</table>\n");
      out.write("			</div>\n");
      out.write("			<!-- 조회 테이블 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("			<!-- list 시작 -->\n");
      out.write("\n");
      out.write("			<div class=\"table-responsive px-2\">\n");
      out.write("				<div class=\"sellList\">\n");
      out.write("					<table class=\"table table-borderless table-hover\">\n");
      out.write("						<thead>\n");
      out.write("							<tr>\n");
      out.write("								<th class=\"table-header\" scope=\"col\" width=\"5%\">번호</th>\n");
      out.write("								<th class=\"table-header\" scope=\"col\" width=\"5%\">구분</th>\n");
      out.write("							<!-- 	<th class=\"table-header\" scope=\"col\" width=\"10%\">상품사진</th> -->\n");
      out.write("								<th class=\"table-header-title\" scope=\"col\" width=\"28%\">제 목</th>\n");
      out.write("								<th class=\"table-header\" scope=\"col\" width=\"8%\">가격</th>\n");
      out.write("								<th class=\"table-header\" scope=\"col\" width=\"10%\">구매요청</th>\n");
      out.write("								<th class=\"table-header\" scope=\"col\" width=\"8%\">구매자</th>\n");
      out.write("								<th class=\"table-header\" scope=\"col\" width=\"*\">작성일</th>\n");
      out.write("								<th class=\"table-header\" scope=\"col\" width=\"*\">거래상태</th>\n");
      out.write("								<!-- <th class=\"table-header\" scope=\"col\" width=\"*\">결제상태</th>  -->\n");
      out.write("							</tr>\n");
      out.write("						</thead>\n");
      out.write("						<tbody class=\"text-center\">\n");
      out.write("\n");
      out.write("							");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("							<!-- sellList  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("						</tbody>\n");
      out.write("					</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("					<!-- 페이지네이션 시작 -->\n");
      out.write("					<!-- <div class=\"pagination\">\n");
      out.write("						<input type=\"hidden\" id=\"PAGE\" name=\"PAGE\" value=\"1\"> <input\n");
      out.write("							type=\"hidden\" id=\"CNT_PER_PAGE\" name=\"CNT_PER_PAGE\" value=\"10\">\n");
      out.write("						<input type=\"hidden\" id=\"START_INDEX\" name=\"START_INDEX\" value=\"\">\n");
      out.write("						<input type=\"hidden\" id=\"END_INDEX\" name=\"END_INDEX\" value=\"\">\n");
      out.write("						<li class=\"page-item arr\"><a class=\"page-link\"\n");
      out.write("							href=\"javascript:fnMovePage(1, fnSearch, 'pagination');\"\n");
      out.write("							aria-label=\"Previous\"> <span class=\"visually-hidden\">처음으로</span>\n");
      out.write("								<span aria-hidden=\"true\"><i\n");
      out.write("									class=\"las la-angle-double-left\"></i></span>\n");
      out.write("						</a></li>\n");
      out.write("						<li class=\"page-item active\"><a class=\"page-link\"\n");
      out.write("							href=\"javascript:fnMovePage(1, fnSearch, 'pagination');\">1</a></li>\n");
      out.write("						<li class=\"page-item arr\"><a class=\"page-link\"\n");
      out.write("							href=\"javascript:fnMovePage(1, fnSearch, 'pagination');\"\n");
      out.write("							aria-label=\"NextEnd\"> <span class=\"visually-hidden\">다음으로</span>\n");
      out.write("								<span aria-hidden=\"true\"><i\n");
      out.write("									class=\"las la-angle-double-right\"></i></span>\n");
      out.write("						</a></li>\n");
      out.write("					</div> -->\n");
      out.write("					<!-- //페이지네이션 끝  -->\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("			<!-- list 끝   -->\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		<!-- 컨테이너 끝  -->\n");
      out.write("	</div>\n");
      out.write("	<!-- 컨텐츠 끝 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Footer -->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\n");
      out.write("	<!-- //Footer -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/history/dealsellList_ver4.jsp(267,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("sellList");
      // /WEB-INF/history/dealsellList_ver4.jsp(267,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/history/dealsellList_ver4.jsp(267,7) '${sellList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sellList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\n");
            out.write("								<tr id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.product_state}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("									<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.deal_number }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("									<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.dealType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("								<!-- 	<td><img alt=\"\" src=\"https://i.imgur.com/5Aqgz7o.jpg\"\n");
            out.write("										width=\"50\" height=\"50\"></td> -->\n");
            out.write("									<td><a\n");
            out.write("										href=\"/ongo/dealRead.do?deal_number=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.deal_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&state=READ\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.board_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\n");
            out.write("									<td>");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</td>\n");
            out.write("									<td>\n");
            out.write("										<button class=\"showReqID\">요청ID보기</button>\n");
            out.write("									</td>\n");
            out.write("									");
            if (_jspx_meth_c_005fchoose_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\n");
            out.write("									<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.write_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("									<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.product_state }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("									");
            out.write("\n");
            out.write("\n");
            out.write("\n");
            out.write("								</tr>\n");
            out.write("\n");
            out.write("\n");
            out.write("								<!-- 거래요청 tr = reqtr -->\n");
            out.write("								<tr id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.deal_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"display: none;\">\n");
            out.write("									<td colspan=\"8\">\n");
            out.write("										<table>\n");
            out.write("											<thead>\n");
            out.write("												<tr>\n");
            out.write("													<th scope=\"col\" width=\"10%\">글번호</th>\n");
            out.write("													<th scope=\"col\" width=\"20%\">날짜</th>\n");
            out.write("													<th scope=\"col\" width=\"30%\">요청ID</th>\n");
            out.write("													<th scope=\"col\" width=\"*\">거래하기</th>\n");
            out.write("												</tr>\n");
            out.write("											</thead>\n");
            out.write("\n");
            out.write("											<tbody class=\"reqdata\">\n");
            out.write("												<!-- ajax 데이터가 출력될 부분 -->\n");
            out.write("\n");
            out.write("											</tbody>\n");
            out.write("										</table>\n");
            out.write("									</td>\n");
            out.write("								</tr>\n");
            out.write("\n");
            out.write("\n");
            out.write("							");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/history/dealsellList_ver4.jsp(276,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.product_price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/history/dealsellList_ver4.jsp(276,13) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###원");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("										");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("										");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("									");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/history/dealsellList_ver4.jsp(282,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.product_state=='판매중' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("											<td>-</td>\n");
          out.write("\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("											<td><span class=\"blue-bold\"> <a\n");
          out.write("													class=\"id-link dropdown-toggle\" href=\"#\" role=\"button\"\n");
          out.write("													data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
          out.write("														");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.buyer_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </a> \n");
          out.write("													");
          if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write(" \n");
          out.write("													\n");
          out.write("											</span></td>\n");
          out.write("										");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("														");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("														");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\n");
          out.write("													");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/history/dealsellList_ver4.jsp(292,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.product_state=='판매완료' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("															<!-- <ul class=\"dropdown-menu\">\n");
          out.write("																<li><a class=\"dropdown-item\" href=\"#\">쪽지보내기</a></li> \n");
          out.write("																</li>\n");
          out.write("															</ul> -->\n");
          out.write("														");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /WEB-INF/history/dealsellList_ver4.jsp(298,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.product_state=='거래진행중' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("														<ul class=\"dropdown-menu\">\n");
          out.write("															<li><a class=\"dropdown-item\"\n");
          out.write("																href=\"/ongo/payment/payRequest?seller_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&buyer_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.buyer_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&board_number=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.deal_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&product_price=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellList.product_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">결제요청하기</a>\n");
          out.write("															</li>\n");
          out.write("														<!-- 	<li><a class=\"dropdown-item\" href=\"#\">쪽지보내기</a></li>  -->\n");
          out.write("														</ul>\n");
          out.write("													");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }
}
