/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-26 00:56:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.Auction;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AuctionWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css\" />\n");
      out.write("<html>\n");
      out.write("<head> </head>\n");
      out.write("<body onload=\"글등록후 수정불가능!!!\">\n");
      out.write("<!-- 이 아래부터  content부분부터 복사해서 붙여넣기 하시면 됩니다. 하단 footer부분 인클루트 시켜주세요 -->\n");
      out.write(" <form action=\"/ongo/auctionWrite.do\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("<!-- content -->\n");
      out.write("<div id=\"contents\">\n");
      out.write("        <!-- title -->\n");
      out.write("        \n");
      out.write("        <div class=\"sub_top\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("          		<input type=hidden hits=0,auction_category=null,end_price=0,current_price=0>\n");
      out.write("                <h1>경매등록</h1>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- //title -->\n");
      out.write("        <!-- 게시판 -->\n");
      out.write("       <div class=\"container\">\n");
      out.write("   								<!-- 아이디 세션에서 가져와야함 -->\n");
      out.write("   								<div class=\"grid-item colspan2\">\n");
      out.write("							<label for=\"HOFS_DTADR\">작성자</label>\n");
      out.write("							<div class=\"tbl-basic-td\">\n");
      out.write("								<div class=\"input-wrap w100\">\n");
      out.write("								<label>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<input type=\"hidden\" id=\"member_id\" name=\"member_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("								</label>\n");
      out.write("									</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("      <input type=\"hidden\" >\n");
      out.write("      <input type=\"hidden\">\n");
      out.write("      <div class=\"cont-box-inner\">\n");
      out.write("        \n");
      out.write("        <div class=\"tbl grid-layout grid2\">\n");
      out.write("        	\n");
      out.write("          <div class=\"grid-item colspan2\">\n");
      out.write("            <label for=\"select_target_1\">상태</label>\n");
      out.write("            <div class=\"tbl-basic-td\">\n");
      out.write("              <div class=\"input-wrap w20\" >\n");
      out.write("                <select class=\"form-select grid-input\" title=\"상태\" name=\"auction_state\">\n");
      out.write("                 <option value=\"경매중\">경매진행중</option><!--보편적으로 0이 false 1이 true  -->\n");
      out.write("            <!--      <option value=\"경매완료\">경매완료</option>  -->\n");
      out.write("                </select>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("             	\n");
      out.write("          <div class=\"grid-item colspan2\">\n");
      out.write("            <label for=\"select_target_1\">카테고리</label>\n");
      out.write("            <div class=\"tbl-basic-td\">\n");
      out.write("              <div class=\"input-wrap w20\" >\n");
      out.write("                <select class=\"form-select grid-input\" title=\"카테고리\" name=\"auction_category\">\n");
      out.write("                 <option value=\"가전\">가전</option><!--보편적으로 0이 false 1이 true  -->\n");
      out.write("                 <option value=\"컴퓨터\">컴퓨터</option> \n");
      out.write("                </select>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"grid-item colspan2\">\n");
      out.write("            <label for=\"HOFS_DTADR\" id=\"auction_title\" >제목</label>\n");
      out.write("            <div class=\"tbl-basic-td\">\n");
      out.write("              <div class=\"input-wrap w100\">\n");
      out.write("                <input class=\"grid-input\" type=\"text\"  maxlength=\"50\" title=\"타이틀\" name=\"auction_title\">\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          </div>\n");
      out.write("          <div class=\"grid-item colspan2\">\n");
      out.write("            <label for=\"HOFS_DTADR\" >경매</label>\n");
      out.write("            <div class=\"tbl-basic-td\">\n");
      out.write("              <div class=\"input-wrap w30 me-4\">\n");
      out.write("              <div> 시작가   </div>\n");
      out.write("              <input id=\"start_price\" name=\"start_price\" class=\"bid-start\" type=\"text\"  maxlength=\"50\" title=\"시작가\"> \n");
      out.write("              <h6 >!경고! 가격은 등록후 수정불가능합니다.</h6>\n");
      out.write("              \n");
      out.write("                <div> 최소가   </div>\n");
      out.write("              <input id=\"min_price\" name=\"min_price\" class=\"bid-start\" type=\"text\"  maxlength=\"50\" title=\"최소가\"> \n");
      out.write("            \n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("         \n");
      out.write("          \n");
      out.write("          <div class=\"grid-item colspan2\">\n");
      out.write("            <label for=\"HOFS_INTR_MTRL_CNTS\">사이즈(상세스펙)</label>\n");
      out.write("            <div class=\"tbl-basic-td\">\n");
      out.write("              <div class=\"input-wrap w100\">\n");
      out.write("                <textarea name=\"board_content\" id=\"board_content\"  class=\"grid-input\" role=\"textbox\"  maxlength=\"500\" rows=\"5\"></textarea>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        \n");
      out.write("          <div class=\"grid-item colspan2\">\n");
      out.write("            <label for=\"HOFS_DTADR\">첨부파일</label>\n");
      out.write("            <div id=\"list_photo\" class=\"tbl-basic-td\">\n");
      out.write("              <div class=\"input-wrap w100\">\n");
      out.write("                  <input type=\"file\" class=\"form-control\" id=\"list_photo\" name=\"files\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AuctionRead.list_photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("     \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("   \n");
      out.write("  			<div class=\"btn-area\">\n");
      out.write("  			<!--글등록   -->\n");
      out.write("       <button class=\"btn btn-primary btn-large\" type=\"submit\" onclick=\"location.href='/ongo/auction/auctionwrite'\">글등록</button>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("        </div>\n");
      out.write("      \n");
      out.write("   </form>\n");
      out.write("   \n");
      out.write("<!-- // content -->\n");
      out.write("\n");
      out.write(" <!-- modal -->\n");
      out.write("	<!-- Footer -->\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\n");
      out.write("	<!-- //Footer -->\n");
      out.write("<!-- //modal -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
