/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-26 00:44:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/DevelUp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DevelUp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1671969684817L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("/*쪽지 top*/\n");
      out.write(".notenew{position: absolute; transform: scale(.7);transform-origin: top right; right: 11px; margin-top: -0.20rem; color: #fff; \n");
      out.write("		background-color: #dc3545; display: inline-block; padding: 0.25em 0.4em;font-size:85%; font-weight: 700; line-height: 1; border-radius: 0.35rem; }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- header -->\n");
      out.write("<div id=\"header\">\n");
      out.write("\n");
      out.write("  <!-- top menu -->\n");
      out.write("  <div class=\"top_menu\">\n");
      out.write("    <div class=\"container d-flex flex-row justify-content-between\">\n");
      out.write("      <ul class=\"top_menu_left\">\n");
      out.write("        <li> TEAM Devel-Up(김규민,김윤희,김태원,박소정,손성민,최경민)</li>\n");
      out.write("      </ul>\n");
      out.write("      <ul class=\"top_menu_right justify-content-end\">\n");
      out.write("		<!-- 규민님 쪽지소켓 <span class=\"badge rounded-pill bg-primary\" id=\"unreadCheck\"></span> -->\n");
      out.write("			<!-- c 콜론 이게 jstl 상단에 태그 달아줄것-->\n");
      out.write("			");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("  \n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  <!--// top menu -->\n");
      out.write("\n");
      out.write("  <div class=\"head\">\n");
      out.write("    <div class=\"container d-flex flex-row justify-content-between\">\n");
      out.write("      <!--logo-wrap-->\n");
      out.write("      <div class=\"logo-wrap\" >\n");
      out.write("        <h1 class=\"logo\"><a href=\"/ongo/index.do\" ><img src=\"/ongo/images/logo.png\" alt=\"온라인 고물상\"></a>\n");
      out.write("        </h1>\n");
      out.write("      </div>\n");
      out.write("      <!--// logo-wrap-->\n");
      out.write("\n");
      out.write("      <!--nav-->\n");
      out.write("      <div id=\"gnb\" class=\"d-flex justify-content-center\">\n");
      out.write("        <ul class=\"dep1\">\n");
      out.write("          <li>\n");
      out.write("           <a id=\"siTitle\" href=\"/ongo/auction/auctionBoard?auction_category=all\" onmouseover=\"menuover(this);\" ><span >경매</span></a>\n");
      out.write("          </li>\n");
      out.write("\n");
      out.write("          <li>\n");
      out.write("            <a id=\"siTitle\" href=\"/ongo/deal_listAll3.do?dealType=all\" onmouseover=\"menuover(this);\" ><span >중고거래</span></a>\n");
      out.write("            <!-- onclick=\"location.href='deal.html'\" -->\n");
      out.write("            <div class=\"dep2_wrap\">\n");
      out.write("              <div class=\"dep2_left\">\n");
      out.write("                <span>중고거래</span>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"dep2_right\" onmouseleave=\"menuout();\">\n");
      out.write("                <div class=\"dep2_right_li\">\n");
      out.write("                  <span class=\"dep2_tit\" ><a href=\"#\" >중고</a></span>\n");
      out.write("                  <ul class=\"dep2_link\">\n");
      out.write("                    <li><a href=\"#\" onclick=\"location.href='/ongo/deal_listAll3.do?dealType=중고'\">중고</a></li>\n");
      out.write("                    <li><a href=\"#\" onclick=\"location.href='/ongo/deal_listAll3.do?dealType=나눔'\">나눔</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </li>\n");
      out.write("        <li>\n");
      out.write("   <a id=\"siTitle\" href=\"/ongo/cooperation/list\" ><span >협력업체</span></a>\n");
      out.write("          </li>\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"util d-flex justify-content-end\">\n");
      out.write("        <button type=\"button\" class=\"sitemap\" data-bs-toggle=\"modal\" data-bs-target=\"#sitemapModal\">\n");
      out.write("          <span class=\"visually-hidden\">사이트맵 바로가기</span>\n");
      out.write("          <span></span>\n");
      out.write("          <span></span>\n");
      out.write("          <span></span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <!--//nav-->\n");
      out.write("    </div>\n");
      out.write("    <!-- nav Modal -->\n");
      out.write("    <div class=\"modal fade\" id=\"sitemapModal\" >\n");
      out.write("      <div class=\"modal-dialog modal-fullscreen\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("          <div class=\"modal-body\">\n");
      out.write("            <div class=\"head\">\n");
      out.write("              <div class=\"container d-flex flex-row justify-content-between\">\n");
      out.write("                <!--logo-wrap-->\n");
      out.write("                <div class=\"logo-wrap\">\n");
      out.write("                  <h1 class=\"logo\"><a href=\"#\"><img src=\"/ongo/images/logo.png\" alt=\"온라인 고물상\"></a></h1>\n");
      out.write("                </div>\n");
      out.write("                <!--// logo-wrap-->\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"sitemap_cont container\">\n");
      out.write("              \n");
      out.write("              <div class=\"sitemap_li d-flex\">\n");
      out.write("                <h2>경매</h2>\n");
      out.write("                <div class=\"sitemap_depth2_wrap\">\n");
      out.write("                  <div class=\"sitemap_depth2\">\n");
      out.write("                    <a href=\"#\" class=\"sitemap_depth2_tit\" ><span onclick=\"pageMove(this, true)\">경매</span></a>\n");
      out.write("                   \n");
      out.write("                  </div>\n");
      out.write("             \n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"sitemap_li d-flex\">\n");
      out.write("                <h2>중고거래</h2>\n");
      out.write("                <div class=\"sitemap_depth2_wrap\">\n");
      out.write("                  <div class=\"sitemap_depth2\">\n");
      out.write("                    <a href=\"/ongo/deal_listAll3.do?dealType=중고\" class=\"sitemap_depth2_tit\" ><span onclick=\"\">중고</span></a>\n");
      out.write("                    <!-- <ul class=\"sitemap_depth3 dot_list\">\n");
      out.write("                     <li ><a href=\"#\" >중고상품</a></li>\n");
      out.write("                    </ul> -->\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"sitemap_depth2\">\n");
      out.write("                    <a href=\"/ongo/deal_listAll3.do?dealType=나눔\" class=\"sitemap_depth2_tit\" ><span onclick=\"\">나눔</span></a>\n");
      out.write("                    <!-- <ul class=\"sitemap_depth3 dot_list\">\n");
      out.write("                     <li ><a href=\"#\" >새상품</a></li>\n");
      out.write("                    </ul> -->\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"sitemap_li d-flex\">\n");
      out.write("                <h2>협력업체</h2>\n");
      out.write("                <div class=\"sitemap_depth2_wrap\">\n");
      out.write("                  <div class=\"sitemap_depth2\">\n");
      out.write("                    <a href=\"/ongo/cooperation/list\" class=\"sitemap_depth2_tit\" ><span>협력업체</span></a>\n");
      out.write("                  </div>\n");
      out.write("              	</div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("  ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("              <i class=\"las la-times\"></i>\n");
      out.write("            </button>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>  <!-- // nav Modal -->\n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("<!-- modal -->\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"Modal\" aria-hidden=\"true\">\n");
      out.write("<form name=\"valid_form\" method=\"post\" onsubmit=\"return validate_user_id()\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("            <div class=\"modal-tit\">\n");
      out.write("                <h2 class=\"h3\">쪽지</h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-con\">\n");
      out.write("                <div class=\"tbl grid-layout grid1\">\n");
      out.write("                    <div class=\"grid-item\">\n");
      out.write("                    <label for=\"IUY_CLSS_NM\">수신자</label>\n");
      out.write("                    <div class=\"tbl-basic-td\">\n");
      out.write("                        <div class=\"input-wrap w100\">\n");
      out.write("                            <span><textarea class=\"grid-input\" role=\"textbox\" id=\"receive_id\" name=\"receive_id\" title=\"수신자\" maxlength=\"500\" rows=\"1\" required=\"required\"></textarea></span>\n");
      out.write("                            <input type=\"text\" hidden=\"true\" id=\"send_id\" name=\"send_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"grid-item\">\n");
      out.write("                        <label for=\"IUY_CLSS_CNTS\">내용적기</label>\n");
      out.write("                        <div class=\"tbl-basic-td\">\n");
      out.write("                        <div class=\"input-wrap w100\">\n");
      out.write("                            <div class=\"input-wrap w100\">\n");
      out.write("                            <textarea class=\"grid-input\" role=\"textbox\" id=\"content\" name=\"content\" title=\"쪽지내용 입력\" maxlength=\"500\" rows=\"5\" required=\"required\"></textarea>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"btn-area\">\n");
      out.write("              <button type=\"submit\" class=\"btn btn-warning text-white btn-large\"  data-bs-dismiss=\"modal\" aria-label=\"Close\">전송</button>\n");
      out.write("            </div>\n");
      out.write("            <!-- 닫기버튼 -->\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                <i class=\"las la-times\"></i>\n");
      out.write("            </button>\n");
      out.write("            <!-- //닫기버튼 -->\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("<!-- //modal -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	var socket = \"\";\n");
      out.write("	var receive_id = \"\";\n");
      out.write("	$(document).ready(function(){\n");
      out.write("		if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user!=null }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\n");
      out.write("			receive_id = {\"receive_id\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"}\n");
      out.write("			connect();\n");
      out.write("			unreadCheck();\n");
      out.write("		}//end if\n");
      out.write("	})//end document.ready.function\n");
      out.write("	\n");
      out.write("	function connect(){\n");
      out.write("		var ws = new WebSocket(\"ws://localhost:8088/ongo/myHandler\");\n");
      out.write("		socket = ws;\n");
      out.write("		ws.onopen = function(){\n");
      out.write("			console.log('Info : connection opened.!');\n");
      out.write("			sendNote();\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		ws.onmessage = function (event){\n");
      out.write("			unreadCheck();\n");
      out.write("		}//end on message\n");
      out.write("\n");
      out.write("		ws.onclose = function (event) {console.log('Info : connection closed.!')}\n");
      out.write("		\n");
      out.write("		ws.onerror = function (err) {console.log('Error :',err)}\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	function validate_user_id(){\n");
      out.write("		var valid_id = $(\"#receive_id\").val(); \n");
      out.write("		if(valid_id.toLowerCase()=='admin'){\n");
      out.write("			alert(\"관리자는 발신 전용 입니다.\");\n");
      out.write("			return false;\n");
      out.write("		} else {\n");
      out.write("			document.valid_form.action=\"/ongo/mypage/note/sendnote\";\n");
      out.write("		}\n");
      out.write("	}//end validate_user_id\n");
      out.write("	\n");
      out.write("	function sendNote(){\n");
      out.write("		socket.send(\"new message\");\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function unreadCheck(){\n");
      out.write("		$.ajax({\n");
      out.write("			url : \"/ongo/mypage/note/ajax_checkNewNote\",\n");
      out.write("			type : \"get\",\n");
      out.write("			data : receive_id,\n");
      out.write("			success : function(data){\n");
      out.write("				if(data>0){\n");
      out.write("					$(\"#unreadCheck\").removeAttr(\"hidden\");\n");
      out.write("					$(\"#unreadCheck\").html(data);\n");
      out.write("				} else {\n");
      out.write("					$(\"#unreadCheck\").attr(\"hidden\", \"hidden\");\n");
      out.write("					$(\"#unreadCheck\").html(\"\");\n");
      out.write("				}\n");
      out.write("			},//end success\n");
      out.write("			error : function(obj,msg,statusMsg){\n");
      out.write("				alert(\"오류발생\"+statusMsg);\n");
      out.write("			}//end error\n");
      out.write("		})//end ajax\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			 ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("          	 ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/include/top.jsp(27,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user==null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("          	  <li><a href=\"/ongo/member/login.do\"><i class=\"las la-unlock\"></i> 로그인</a></li>\n");
          out.write("          	  <li><a href=\"/ongo/member/join1.do\"><i class=\"las la-user\"></i>회원가입</a></li>\n");
          out.write("          	 ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("          	  <li><i class=\"las la-envelope\"></i><span id=\"unreadCheck\" class=\"notenew\" hidden=\"hidden\"></span></li>\n");
          out.write("          	  <li><i class=\"las la-user\"></i><b>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b>&nbsp;님</li>\n");
          out.write("              <li><a href=\"/ongo/member/logout.do\">로그아웃</a></li>\n");
          out.write("             ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/include/top.jsp(80,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user!=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \n");
          out.write("    ");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("    ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('\n');
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write(' ');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/include/top.jsp(81,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.member_role=='1' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \n");
          out.write("          <li>\n");
          out.write("            <a id=\"siTitle\" href=\"/ongo/history/myongo\" onmouseover=\"menuover(this);\"><span >나의온고</span></a>\n");
          out.write("            <div class=\"dep2_wrap\">\n");
          out.write("              <div class=\"dep2_left\">\n");
          out.write("                <span>나의온고</span>\n");
          out.write("              </div>\n");
          out.write("              <div class=\"dep2_right\" onmouseleave=\"menuout();\">\n");
          out.write("              \n");
          out.write("             <!-- 수정할부분 -->\n");
          out.write("                <div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"#\">경매관리</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li><a href=\"/ongo/detail/auctionsellList?member_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&auction_state=all\">경매관리</a></li>\n");
          out.write("                   ");
          out.write("\n");
          out.write("                  </ul>                 \n");
          out.write("                </div>\n");
          out.write("                <div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"#\">중고거래관리</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li><a href=\"/ongo/history/dealsellList?member_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&product_state=all\">판매관리</a></li>\n");
          out.write("                    <li><a href=\"/ongo/history/dealbuyList?member_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&product_state=all\">구매관리</a></li> \n");
          out.write("                  </ul>\n");
          out.write("                </div>\n");
          out.write("                 <div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"/ongo/payment/paymentlist\">결제내역</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li><a href=\"/ongo/payment/paymentlist?member_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">결제내역조회</a></li>\n");
          out.write("                     \n");
          out.write("                  </ul>\n");
          out.write("                </div>\n");
          out.write("                <div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"/ongo/member/usermypage\" >마이페이지</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li>\n");
          out.write("                    <a href=\"/ongo/member/usermypage?user_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">정보수정</a></li>\n");
          out.write("                  </ul>\n");
          out.write("                </div>\n");
          out.write("                <div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"#\" >쪽지함</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li><a href=\"#\" title=\"쪽지보내기 팝업\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">쪽지보내기</a></li>\n");
          out.write("                    <li><a href=\"#\" onclick=\"location.href='/ongo/mypage/note/receivebox?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">받은쪽지함</a></li>\n");
          out.write("                    <li><a href=\"#\" onclick=\"location.href='/ongo/mypage/note/sendbox?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">보낸쪽지함</a></li>\n");
          out.write("                  </ul>\n");
          out.write("                </div>\n");
          out.write("              </div>\n");
          out.write("            </div>\n");
          out.write("          </li>\n");
          out.write("    <li>\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/include/top.jsp(132,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.member_role=='2' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \n");
          out.write("          <li>\n");
          out.write("            <a id=\"siTitle\" href=\"#\" onmouseover=\"menuover(this);\"><span >나의온고</span></a>\n");
          out.write("            <div class=\"dep2_wrap\">\n");
          out.write("              <div class=\"dep2_left\">\n");
          out.write("                <span>나의온고</span>\n");
          out.write("              </div>\n");
          out.write("              <div class=\"dep2_right\" onmouseleave=\"menuout();\">\n");
          out.write("              \n");
          out.write("             <!-- 수정할부분 -->\n");
          out.write("				<div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"#\" >거래요청목록</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li>\n");
          out.write("                    <a href=\"/ongo/recycle/list?receive_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">거래요청목록</a></li>\n");
          out.write("                  </ul>\n");
          out.write("                </div>\n");
          out.write("                <div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"#\" >마이페이지</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li>\n");
          out.write("                    <a href=\"/ongo/member/usermypage?user_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">정보수정</a></li>\n");
          out.write("                  </ul>\n");
          out.write("                </div>\n");
          out.write("                <div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"#\" >쪽지함</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li><a href=\"#\" title=\"쪽지보내기 팝업\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">쪽지보내기</a></li>\n");
          out.write("                    <li><a href=\"#\" onclick=\"location.href='/ongo/mypage/note/receivebox?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">받은쪽지함</a></li>\n");
          out.write("                    <li><a href=\"#\" onclick=\"location.href='/ongo/mypage/note/sendbox?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">보낸쪽지함</a></li>\n");
          out.write("                  </ul>\n");
          out.write("                </div>\n");
          out.write("              </div>\n");
          out.write("            </div>\n");
          out.write("          </li>\n");
          out.write("    <li>\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/include/top.jsp(170,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.member_role=='99'  }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("  <li>\n");
          out.write("            <a id=\"siTitle\" href=\"/ongo/member/memberboard.do\" onmouseover=\"menuover(this);\"><span >관리자</span></a>\n");
          out.write("            <div class=\"dep2_wrap\">\n");
          out.write("              <div class=\"dep2_left\">\n");
          out.write("                <span>관리자메뉴</span>\n");
          out.write("              </div>\n");
          out.write("              <div class=\"dep2_right\" onmouseleave=\"menuout();\">\n");
          out.write("               <div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"#\">회원관리</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li><a href=\"/ongo/member/memberboard.do\">회원목록</a></li>\n");
          out.write("                  </ul>\n");
          out.write("                </div>\n");
          out.write("                <!-- \n");
          out.write("                <div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"#\">게시판관리</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li ><a href=\"/ongo/member/memberserviceboard.do\">게시물통합관리</a></li>\n");
          out.write("                  </ul>\n");
          out.write("                </div> -->\n");
          out.write("                <div class=\"dep2_right_li\">\n");
          out.write("                  <span class=\"dep2_tit\" ><a href=\"#\">쪽지함</a></span>\n");
          out.write("                  <ul class=\"dep2_link\">\n");
          out.write("                    <li ><a href=\"/ongo/mypage/note/sendbox?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">보낸쪽지함</a></li>\n");
          out.write("                  </ul>\n");
          out.write("                </div>\n");
          out.write("              </div>\n");
          out.write("            </div>\n");
          out.write(" ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/include/top.jsp(265,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user!=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \n");
          out.write(" <!-- 세션에 저장된 member_role 값이 '1' 이면일반 유저라면 메뉴에 '마이페이지'가 생성  --> \n");
          out.write("    ");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /WEB-INF/include/top.jsp(267,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.member_role=='1' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("    \n");
          out.write("          <div class=\"sitemap_li d-flex\">\n");
          out.write("                <h2>나의온고</h2>\n");
          out.write("                <div class=\"sitemap_depth2_wrap\">\n");
          out.write("                  <div class=\"sitemap_depth2\">\n");
          out.write("                    <a href=\"#\" class=\"sitemap_depth2_tit\"><span onclick=\"pageMove(this, true)\">경매관리</span></a>\n");
          out.write("                    <ul class=\"sitemap_depth3 dot_list\">\n");
          out.write("                        <li><a href=\"/ongo/detat/dealsellList\">판매관리</a></li>\n");
          out.write("                   	 	<!-- <li><a href=\"/ongo/detail/auctionbuyList\">구매관리</a></li>    -->\n");
          out.write("                    </ul>\n");
          out.write("                  </div>\n");
          out.write("                  \n");
          out.write("                  <div class=\"sitemap_depth2\">\n");
          out.write("                    <a href=\"#\" class=\"sitemap_depth2_tit\"><span onclick=\"pageMove(this, true)\">중고거래관리</span></a>\n");
          out.write("                    <ul class=\"sitemap_depth3 dot_list\">\n");
          out.write("	                   <li><a href=\"/ongo/history/dealsellList?member_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&product_state=판매중\">판매관리</a></li>\n");
          out.write("	                   <li><a href=\"#\">구매관리</a></li> \n");
          out.write("                    </ul>\n");
          out.write("                  </div>\n");
          out.write("                 <div class=\"sitemap_depth2\">\n");
          out.write("                    <a href=\"#\" class=\"sitemap_depth2_tit\"><span onclick=\"pageMove(this, true)\">결제내역</span></a>\n");
          out.write("                    <ul class=\"sitemap_depth3 dot_list\">\n");
          out.write("	                    <li><a href=\"/ongo/payment/paymentlist\">결제내역조회</a></li>\n");
          out.write("                    \n");
          out.write("                    </ul>\n");
          out.write("                  </div>\n");
          out.write("                  <div class=\"sitemap_depth2\">\n");
          out.write("                    <a href=\"#\" class=\"sitemap_depth2_tit\"><span onclick=\"pageMove(this, true)\">정보수정</span></a>\n");
          out.write("                    <ul class=\"sitemap_depth3 dot_list\">\n");
          out.write("                      <li ><a href=\"#\" >정보수정</a></li>\n");
          out.write("                    </ul>\n");
          out.write("                  </div>\n");
          out.write("                  <div class=\"sitemap_depth2\">\n");
          out.write("                    <a href=\"#\" class=\"sitemap_depth2_tit\"><span onclick=\"pageMove(this, true)\">쪽지함</span></a>\n");
          out.write("                    <ul class=\"sitemap_depth3 dot_list\">\n");
          out.write("                      <li ><a href=\"#\" title=\"쪽지보내기 팝업\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">쪽지보내기</a></li>\n");
          out.write("                      <li ><a href=\"/ongo/mypage/note/receivebox?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" >받은쪽지함</a></li>\n");
          out.write("                      <li ><a href=\"/ongo/mypage/note/sendbox?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" >보낸쪽지함</a></li>\n");
          out.write("                    </ul>\n");
          out.write("                  </div>\n");
          out.write("                </div>\n");
          out.write("                </div>\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /WEB-INF/include/top.jsp(310,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.member_role=='99'  }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("		             <div class=\"sitemap_li d-flex\">\n");
          out.write("		                <h2>관리자</h2>\n");
          out.write("		                <div class=\"sitemap_depth2_wrap\">\n");
          out.write("		                  <div class=\"sitemap_depth2\">\n");
          out.write("		                    <a href=\"#\" class=\"sitemap_depth2_tit\"><span onclick=\"/ongo/member/memberboard.do\">회원관리</span></a>\n");
          out.write("		                    <ul class=\"sitemap_depth3 dot_list\">\n");
          out.write("		                      <li ><a href=\"#\" >회원목록</a></li>\n");
          out.write("		                    </ul>\n");
          out.write("		                  </div>\n");
          out.write("		                  <!-- \n");
          out.write("		                  <div class=\"sitemap_depth2\">\n");
          out.write("		                    <a href=\"/ongo/member/memberserviceboard.do\" class=\"sitemap_depth2_tit\"><span onclick=\"pageMove(this, true)\">게시판관리</span></a>\n");
          out.write("		                    <ul class=\"sitemap_depth3 dot_list\">\n");
          out.write("		                      <li ><a href=\"/ongo/member/memberserviceboard.do\" >게시물통합관리</a></li>\n");
          out.write("		                    </ul>\n");
          out.write("		                  </div> -->\n");
          out.write("		                   <div class=\"sitemap_depth2\">\n");
          out.write("		                    <a href=\"#\" class=\"sitemap_depth2_tit\"><span onclick=\"pageMove(this, true)\">쪽지함</span></a>\n");
          out.write("		                    <ul class=\"sitemap_depth3 dot_list\">\n");
          out.write("		                      <li ><a href=\"/ongo/mypage/note/sendbox?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" >보낸쪽지함</a></li>\n");
          out.write("		                    </ul>\n");
          out.write("		                  </div>\n");
          out.write("		                  \n");
          out.write("		                </div>\n");
          out.write("		              </div>\n");
          out.write("		       ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }
}
