/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-26 00:44:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainLayout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/DevelUp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DevelUp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1671969684817L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no\"> \n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"https://openapi.map.naver.com/openapi/v3/maps.js?ncpClientId=nfflwtq6kn\"></script>\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"/ongo/common/css/main.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- content -->\n");
      out.write("<div id=\"contents\" class=\"main\">\n");
      out.write("<div >\n");
      out.write("    <section class=\"visual section active\">\n");
      out.write("      <!-- 온고소개 -->\n");
      out.write("      <div class=\"introduce\">\n");
      out.write("        <div class=\"title_box\">\n");
      out.write("          <h2>\n");
      out.write("            <span class=\"blue\">보다 더 · 당신의 일상과 가깝게</span>\n");
      out.write("            <span class=\"h1\">온라인 고물상</span>\n");
      out.write("          </h2>\n");
      out.write("          <p class=\"gray_tt\">재활용 되지 않는 대형 쓰레기\n");
      out.write("          생활 페기물이 버려지지 않고 다시 쓰일 수 있도록, 온고의 서비스를 이용해 보세요.\n");
      out.write("          </p>\n");
      out.write("        </div>\n");
      out.write("        <ul class=\"nav nav-tabs\" id=\"introTab\" role=\"tablist\">\n");
      out.write("          <li class=\"nav-item\" role=\"presentation\">\n");
      out.write("            <button class=\"nav-link active\" id=\"intro1-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#intro1\" type=\"button\"\n");
      out.write("              role=\"tab\" aria-controls=\"intro1\" aria-selected=\"true\">협력업체</button>\n");
      out.write("          </li>\n");
      out.write("           <li class=\"nav-item\" role=\"presentation\">\n");
      out.write("            <button class=\"nav-link\" id=\"intro_auction\" data-bs-toggle=\"tab\" data-bs-target=\"#intro2\" type=\"button\"\n");
      out.write("              role=\"tab\" aria-controls=\"intro1\" aria-selected=\"true\">경매</button>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\" role=\"presentation\">\n");
      out.write("            <button class=\"nav-link\" id=\"intro2-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#intro3\" type=\"button\"\n");
      out.write("              role=\"tab\" aria-controls=\"intro2\" aria-selected=\"false\">중고거래</button>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"tab-content\">\n");
      out.write("          <div class=\"tab-pane fade show  active\" id=\"intro1\" aria-labelledby=\"intro1-tab\">\n");
      out.write("            <div id=\"intro1slider\" class=\"carousel carousel-dark introslider\" data-bs-ride=\"carousel\"\n");
      out.write("              data-bs-interval=\"10000000\">\n");
      out.write("              <div class=\"carousel-inner\">\n");
      out.write("              </div>\n");
      out.write("              <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#intro1slider\" data-bs-slide=\"prev\" onclick=\"markerChg()\">\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\n");
      out.write("              </button>\n");
      out.write("              <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#intro1slider\" data-bs-slide=\"next\" onclick=\"markerChg()\">\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\n");
      out.write("              </button>\n");
      out.write("            </div>\n");
      out.write("            <!-- <div class=\"map map1\">\n");
      out.write("              <ul>\n");
      out.write("                <li class=\"seoul\"><button type=\"button\" class=\"btn active\">소정자원</button></li>\n");
      out.write("                <li class=\"daeduck\"><button type=\"button\" class=\"btn\">태원강철</button></li>\n");
      out.write("                <li class=\"gyeonggi\"><button type=\"button\" class=\"btn \">윤희자원</button></li>\n");
      out.write("                <li class=\"yongin\"><button type=\"button\" class=\"btn\">규민강철</button></li>\n");
      out.write("                <li class=\"busan\"><button type=\"button\" class=\"btn\">경민강철</button></li>\n");
      out.write("                <li class=\"jeju\"><button type=\"button\" class=\"btn\">성민자원</button></li>\n");
      out.write("              </ul> -->\n");
      out.write("            <div id=\"map\" class = \"map map1\" style=\"position: absolute;\">\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"tab-pane fade\" id=\"intro2\" aria-labelledby=\"intro2-tab\">\n");
      out.write("            <div id=\"intro2slider\" class=\"carousel carousel-dark introslider\" data-bs-ride=\"carousel\"\n");
      out.write("              data-bs-interval=\"10000000\">\n");
      out.write("              <div class=\"carousel-inner\" id=\"carousel-inner_auction\">\n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("<!--경매  _______________________________________________________________________________________________-->\n");
      out.write("              <script type=\"text/javascript\">\n");
      out.write("              	$(document).ready(function () {\n");
      out.write("              		$(\"#intro_auction\").click(function () {\n");
      out.write("						/* dealType = \"all\"; */\n");
      out.write("						/* $(this).attr(\"class\", \"active\"); //클래스속성에 active속성부여  */\n");
      out.write("					$.ajax({\n");
      out.write("						url: \"/ongo/auction/mainlayout\",\n");
      out.write("						type: \"get\",\n");
      out.write("						data:{\n");
      out.write("							/* \"dealType\": dealType, */\n");
      out.write("						},\n");
      out.write("						success: function(ajaxlist) {\n");
      out.write("							mydata = \"\";\n");
      out.write("							for (var i = 0; i < ajaxlist.length; i++) {\n");
      out.write("								// active가 안되어있어서 결과가 안나왔었음!!\n");
      out.write("							 if(i==0){\n");
      out.write("								 data = \n");
      out.write("									\n");
      out.write("									 \"<div class='carousel-item active' >\"+\n");
      out.write("						                  \"<h3>제목 : \" + ajaxlist[i].auction_title +  \"</h3>\"+\n");
      out.write("						                  \"<ul class='introlist'>\"+\n");
      out.write("						                  \"<li><span class='introlist_tit'>시작가격</span><span class='introlist_txt'>\" + ajaxlist[i].start_price + \"원</span></li>\"+\n");
      out.write("						                  \"<li><span class='introlist_tit'>현재가격</span><span class='introlist_txt'>\" + ajaxlist[i].current_price + \"원</span></li>\"+\n");
      out.write("						                  \"<li><span class='introlist_tit'>종료시간</span><span class='introlist_txt'>\" + ajaxlist[i].end_date + \"</span></li>\"+\n");
      out.write("						                  \"</ul>\"+\n");
      out.write("						                \"</div>\"\n");
      out.write("							 }else{\n");
      out.write("								data =  \n");
      out.write("									\"<div class='carousel-item' >\"+\n");
      out.write("					                  \"<h3>제목 : \" + ajaxlist[i].auction_title +  \"</h3>\"+\n");
      out.write("					                  \"<ul class='introlist'>\"+\n");
      out.write("					                  \"<li><span class='introlist_tit'>시작가격</span><span class='introlist_txt'>\" + ajaxlist[i].start_price + \"원</span></li>\"+\n");
      out.write("					                  \"<li><span class='introlist_tit'>현재가격</span><span class='introlist_txt'>\" + ajaxlist[i].current_price + \"원</span></li>\"+\n");
      out.write("					                  \"<li><span class='introlist_tit'>종료시간</span><span class='introlist_txt'>\" + ajaxlist[i].end_date + \"</span></li>\"+\n");
      out.write("					                  \"</ul>\"+\n");
      out.write("					                \"</div>\"\n");
      out.write("							 }\n");
      out.write("							 mydata = mydata +data;\n");
      out.write("							}\n");
      out.write("							\n");
      out.write("							$(\"#carousel-inner_auction\").html(mydata); \n");
      out.write("							\n");
      out.write("							\n");
      out.write("						},\n");
      out.write("							error: function (a,b,c) {\n");
      out.write("								alert(c)\n");
      out.write("							}\n");
      out.write("						})//end ajax\n");
      out.write("					})//end clcick\n");
      out.write("              	}) //end ready\n");
      out.write("              		/* $(\"#deal-item\"). */\n");
      out.write("              \n");
      out.write("              </script>\n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              <!--__________________________________________________ -->\n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("                <div class=\"carousel-item active\">\n");
      out.write("                  <h3>\n");
      out.write("                    냉장고128L\n");
      out.write("                    <a href=\"#\" class=\"btn btn-small\"\n");
      out.write("                      target=\"_blank\" title=\"새창\">상세보기<i class=\"las la-external-link-alt\"></i></a>\n");
      out.write("                  </h3>\n");
      out.write("                  <ul class=\"introlist\">\n");
      out.write("                    <li><span class=\"introlist_tit\">주소</span><span class=\"introlist_txt\">서울특별시 강남구</span></li>\n");
      out.write("                    <li><span class=\"introlist_tit\">크기</span><span class=\"introlist_txt\">총 49.684㎢</span></li>\n");
      out.write("                    <li><span class=\"introlist_tit\">시작가</span><span class=\"introlist_txt\">50,000원</span></li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"introlink\">\n");
      out.write("                    <span><a href=\"#\">현재입찰가</a></span>\n");
      out.write("                    <span><a href=\"#\">입찰참여</a></span>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"carousel-item \">\n");
      out.write("                  <h3>\n");
      out.write("                    컴퓨터\n");
      out.write("                    <a href=\"#\" class=\"btn btn-small\"\n");
      out.write("                      target=\"_blank\" title=\"새창\">상세보기<i class=\"las la-external-link-alt\"></i></a>\n");
      out.write("                  </h3>\n");
      out.write("                  <ul class=\"introlist\">\n");
      out.write("                    <li><span class=\"introlist_tit\">주소</span><span class=\"introlist_txt\">서울특별시 강남구</span></li>\n");
      out.write("                    <li><span class=\"introlist_tit\">크기</span><span class=\"introlist_txt\">총 49.684㎢</span></li>\n");
      out.write("                    <li><span class=\"introlist_tit\">시작가</span><span class=\"introlist_txt\">50,000원</span></li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"introlink\">\n");
      out.write("                    <span><a href=\"#\">현재입찰가</a></span>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#intro2slider\" data-bs-slide=\"prev\">\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\n");
      out.write("              </button>\n");
      out.write("              <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#intro2slider\" data-bs-slide=\"next\">\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\n");
      out.write("              </button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"map map1\">\n");
      out.write("           \n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          \n");
      out.write("          \n");
      out.write("          \n");
      out.write("          <div class=\"tab-pane fade\" id=\"intro3\" aria-labelledby=\"intro3-tab\">\n");
      out.write("            <div id=\"intro3slider\" class=\"carousel carousel-dark introslider\" data-bs-ride=\"carousel\"\n");
      out.write("              data-bs-interval=\"10000000\">\n");
      out.write("              <div class=\"carousel-inner\" id=\"carousel-inner\">\n");
      out.write("              \n");
      out.write("              \n");
      out.write("    <!--중고거래  _______________________________________________________________________________________________-->\n");
      out.write("              <script type=\"text/javascript\">\n");
      out.write("              	$(document).ready(function () {\n");
      out.write("              		$(\"#intro2-tab\").click(function () {\n");
      out.write("						dealType = \"all\";\n");
      out.write("						/* $(this).attr(\"class\", \"active\"); //클래스속성에 active속성부여  */\n");
      out.write("					$.ajax({\n");
      out.write("						url: \"/ongo/dealType_main.do\",\n");
      out.write("						type: \"get\",\n");
      out.write("						data:{\n");
      out.write("							\"dealType\": dealType,\n");
      out.write("						},\n");
      out.write("						success: function(ajaxlist) {\n");
      out.write("							mydata = \"\";\n");
      out.write("							for (var i = 0; i < ajaxlist.length; i++) {\n");
      out.write("								// active가 안되어있어서 결과가 안나왔었음!!\n");
      out.write("							 if(i==0){\n");
      out.write("								 data = \n");
      out.write("									\n");
      out.write("									 \"<div class='carousel-item active'  id='deal-item'>\"+\n");
      out.write("										\"<h3> \"+\n");
      out.write("						                  \n");
      out.write("						                    \"<a href='/ongo/dealRead.do?deal_number=\"+ ajaxlist[i].deal_number +\"&state=READ' class='btn btn-small' target='_blank'\"+\n");
      out.write("						                      \"title='새창'>상세보기<i class='las la-external-link-alt'></i></a>\"+\n");
      out.write("						                  \"</h3>\"+\n");
      out.write("						                  \"<h3>제목 : \" + ajaxlist[i].board_title +  \"</h3>\"+\n");
      out.write("						                  \"<ul class='introlist'>\"+\n");
      out.write("						                  \"<li><span class='introlist_tit'>금액</span><span class='introlist_txt'>\" + ajaxlist[i].product_price + \"원</span></li>\"+\n");
      out.write("						                  \"</ul>\"+\n");
      out.write("						                \"</div>\"\n");
      out.write("							 }else{\n");
      out.write("								data =  \n");
      out.write("									\"<div class='carousel-item'  id='deal-item'>\"+\n");
      out.write("									\"<h3> \"+\n");
      out.write("					                  \n");
      out.write("					                    \"<a href='/ongo/dealRead.do?deal_number=\"+ ajaxlist[i].deal_number +\"&state=READ' class='btn btn-small' target='_blank'\"+\n");
      out.write("					                      \"title='새창'>상세보기<i class='las la-external-link-alt'></i></a>\"+\n");
      out.write("					                  \"</h3>\"+\n");
      out.write("					                  \"<h3>제목 : \" + ajaxlist[i].board_title +  \"</h3>\"+\n");
      out.write("					                  \"<ul class='introlist'>\"+\n");
      out.write("					                  \"<li><span class='introlist_tit'>금액</span><span class='introlist_txt'>\" + ajaxlist[i].product_price + \"원</span></li>\"+\n");
      out.write("					                  \"</ul>\"+\n");
      out.write("					                \"</div>\"\n");
      out.write("							 }\n");
      out.write("							 mydata = mydata +data;\n");
      out.write("							}\n");
      out.write("							\n");
      out.write("							$(\"#carousel-inner\").html(mydata); \n");
      out.write("							\n");
      out.write("							\n");
      out.write("						},\n");
      out.write("							error: function (a,b,c) {\n");
      out.write("								alert(c)\n");
      out.write("							}\n");
      out.write("						})//end ajax\n");
      out.write("					})//end clcick\n");
      out.write("              	}) //end ready\n");
      out.write("              		/* $(\"#deal-item\"). */\n");
      out.write("              \n");
      out.write("              </script>\n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              \n");
      out.write("              <!--__________________________________________________ -->\n");
      out.write("                <div class=\"carousel-item active\" id=\"deal-item\">\n");
      out.write("                  <h3 id=\"main_board_title\">에어컨\n");
      out.write("                    <a href=# class=\"btn btn-small\" target=\"_blank\"  title=\"새창\">상세보기<i class=\"las la-external-link-alt\"></i></a>\n");
      out.write("                  </h3>\n");
      out.write("                  <ul class=\"introlist\">\n");
      out.write("                    <li><span id=\"\" class=\"introlist_tit\">사진</span><span class=\"introlist_txt\">경기도 안산시 상록구</span></li>\n");
      out.write("                  </ul>\n");
      out.write("                  <ul class=\"introlist\">\n");
      out.write("                    <li><span id=\"product_price\" class=\"introlist_tit\">가격</span><span class=\"introlist_txt\">경기도 안산시 상록구</span></li>\n");
      out.write("                    <li><span id=\"board_content\" class=\"introlist_tit\">내용</span><span class=\"introlist_txt\">경기도 안산시 상록구</span></li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"introlink\">\n");
      out.write("                    <span><a href=\"#\">거래요청</a></span>\n");
      out.write("                    <span><a href=\"#\">쪽지보내기</a></span>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("              \n");
      out.write("            \n");
      out.write("              \n");
      out.write("                            \n");
      out.write("              <!--__________________________________________________ -->\n");
      out.write("                <div class=\"carousel-item\" id=\"deal-item\">\n");
      out.write("                  <h3>\n");
      out.write("                    토스터기 나눔\n");
      out.write("                    <a href=# class=\"btn btn-small\" target=\"_blank\"\n");
      out.write("                      title=\"새창\">상세보기<i class=\"las la-external-link-alt\"></i></a>\n");
      out.write("                  </h3>\n");
      out.write("                  <ul class=\"introlist\">\n");
      out.write("                    <li><span class=\"introlist_tit\">주소</span><span class=\"introlist_txt\">경기도 안산시 상록구</span></li>\n");
      out.write("                    <li><span class=\"introlist_tit\">크기</span><span class=\"introlist_txt\">10평</span></li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"introlink\">\n");
      out.write("                    <span><a href=\"#\">거래요청</a></span>\n");
      out.write("                    <span><a href=\"#\">쪽지보내기</a></span>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <!--__________________________________________________ -->\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("                \n");
      out.write("              </div>\n");
      out.write("              <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#intro3slider\" data-bs-slide=\"prev\">\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\n");
      out.write("              </button>\n");
      out.write("              <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#intro3slider\" data-bs-slide=\"next\">\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\n");
      out.write("              </button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"map map2\">\n");
      out.write("            \n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("           \n");
      out.write("         \n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- //온고소개 -->\n");
      out.write("\n");
      out.write("      <!-- 처음이용자 안내 -->\n");
      out.write("      <div class=\"guide\">\n");
      out.write("        <div class=\"title_box white\">\n");
      out.write("          <h2>결제안내</h2>\n");
      out.write("          <p class=\"gray_tt\">온고결제가 아닌 개인 거래시<br/>발생하는 금융사기 조심하세요.</p>\n");
      out.write("        </div>\n");
      out.write("        <ul class=\"nav nav-tabs\" id=\"myTab\" role=\"tablist\">\n");
      out.write("          <li class=\"nav-item\" role=\"presentation\">\n");
      out.write("            <button class=\"nav-link active\" id=\"add-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#add\" type=\"button\"\n");
      out.write("              role=\"tab\" aria-controls=\"add\" aria-selected=\"true\">경매물품 검색</button>\n");
      out.write("          </li>\n");
      out.write("          <li class=\"nav-item\" role=\"presentation\">\n");
      out.write("            <button class=\"nav-link\" id=\"allow-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#allow\" type=\"button\"\n");
      out.write("              role=\"tab\" aria-controls=\"allow\" aria-selected=\"false\">중고거래 검색</button>\n");
      out.write("          </li>\n");
      out.write("        </ul>\n");
      out.write("        <div class=\"tab-content\">\n");
      out.write("          <div class=\"tab-pane fade show active\" id=\"add\" >\n");
      out.write("            <h2 class=\"visually-hidden\">경매물품 검색</h2>\n");
      out.write("            <div class=\"input-group\">\n");
      out.write("              <label for=\"srchWord1\" class=\"form-label visually-hidden\">경매물품 검색</label>\n");
      out.write("              <input type=\"text\" class=\"form-control service_sch\" name=\"srchWord\" id=\"srchWord1\"\n");
      out.write("                title=\"'경매물품' 또는 '상품' 입력\" placeholder=\"'단어' 입력\">\n");
      out.write("              <button id=\"srchWord1-btn\" type=\"button\" class=\"btn btn-search\" onclick=\"fnSearchAddr();\"><span\n");
      out.write("                  class=\"visually-hidden\">검색</span></button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"tab-pane fade\" id=\"allow\">\n");
      out.write("            <h2 class=\"visually-hidden\">중고거래 검색</h2>\n");
      out.write("            <div class=\"input-group\">\n");
      out.write("              <label for=\"srchWord2\" class=\"form-label visually-hidden\">중고거래 검색</label>\n");
      out.write("              <input type=\"text\" class=\"form-control service_sch\" name=\"srchWord\" id=\"srchWord2\" title=\"단어 입력\"\n");
      out.write("                placeholder=\"단어 입력\">\n");
      out.write("              <button id=\"srchWord2-btn\" type=\"button\" class=\"btn btn-search\" onclick=\"fnSearchKsic();\"><span\n");
      out.write("                  class=\"visually-hidden\">검색</span></button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- //처음이용자안내 -->\n");
      out.write("      <!-- 로그인 -->\n");
      out.write("      <div class=\"login\">\n");
      out.write("        \n");
      out.write("          \n");
      out.write("            <div class=\"title_box white\">\n");
      out.write("              <h2>폐가전 무료 수거 방법</h2>\n");
      out.write("              <ul class=\"nav-tabs\" >\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"mt-3 text-white\">\n");
      out.write("              <p>한국전자제품 <a href=\"www.15990903.or.kr\" target=\"_blank\" class=\"text-white\">자원순환공제조합 </a>에서 <br/>\n");
      out.write("              운영하는 폐가전 무상방문수거 서비스를 이용할 수 있습니다.<br/><br/>\n");
      out.write("               폐가전 무료배출은 먼저 인터넷과 모바일, 콜센터\n");
      out.write("               <br/>(전국 1599-0903)를 통해서 폐가전제품 배출 예약은 간단히 할 수 있습니다.<br/><br/>\n");
      out.write("               콜센터 운영시간은 평일 8시부터 18시이고 휴무일은 매주 토일요일 근로자의날, 설 추석 연휴, 신정, 공휴일 처리불가\n");
      out.write("               </p>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          \n");
      out.write("          \n");
      out.write("        \n");
      out.write("      </div>\n");
      out.write("      <!-- //로그인 -->\n");
      out.write("\n");
      out.write("      <!-- 배달중계 -->\n");
      out.write("      <div class=\"stepinfo\">\n");
      out.write("        <div class=\"stepinfo_box\">\n");
      out.write("          <div class=\"title_box white\">\n");
      out.write("            <h2>온고안내</h2>\n");
      out.write("            <p class=\"gray_tt\">온고의 서비스를 확인 하세요!</p>\n");
      out.write("          </div>\n");
      out.write("          <ul>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <p class=\"icon stepicon2\"></p>\n");
      out.write("                <p>흥정을 위한 경매 시스템</p>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <p class=\"icon stepicon3\"></p>\n");
      out.write("                <p>환경도 지키고 돈도 버는 '고테크'</p>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("\n");
      out.write("            <li>\n");
      out.write("              <a href=\"#\">\n");
      out.write("                <p class=\"icon stepicon1\"></p>\n");
      out.write("                <p>공정거래를 위한 협력업체</p>\n");
      out.write("              </a>\n");
      out.write("            </li>\n");
      out.write("            \n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- //  -->\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("   <section class=\"foot section fp-auto-height\">\n");
      out.write("      <!-- 관련사이트 -->\n");
      out.write("      <div class=\"relate\">\n");
      out.write("        <div class=\"main_container\">\n");
      out.write("          <h2>온고 협력업체</h2>\n");
      out.write("          <ul>\n");
      out.write("            <li><a href=\"https://igmyd.co.kr/\" target=\"_blank\">고물연대</a></li>\n");
      out.write("            <li><a href=\"http://www.porart.com\" target=\"_blank\">포털아트</a></li>\n");
      out.write("            <li><a href=\"https://www.kobay.co.kr\" target=\"_blank\">코베이옥션</a></li>\n");
      out.write("            <li><a href=\"https://cafe.naver.com/joonggonara\" target=\"_blank\">중고나라</a></li>\n");
      out.write("            <li><a href=\"https://thecheat.co.kr/\" target=\"_blank\">더치트</a></li>\n");
      out.write("            <li><a href=\"https://www.police.go.kr/www/security/cyber/cyber04.jsp\" target=\"_blank\">사이버 경찰청</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- //관련사이트 -->\n");
      out.write("\n");
      out.write("      <!-- Footer -->\n");
      out.write("      <div class=\"footer section\">\n");
      out.write("        <nav class=\"fnb d-flex\">\n");
      out.write("          <div class=\"main_container\">\n");
      out.write("            <ul>\n");
      out.write("              <li class=\"on\"><strong><a href=\"#\">개인정보처리방침</a></strong></li>\n");
      out.write("              <li><a href=\"#\">이용약관</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("        </nav>\n");
      out.write("        <div class=\"addr d-flex\">\n");
      out.write("          <div class=\"main_container\">\n");
      out.write("            <div class=\"logo-wrap\">\n");
      out.write("              <div class=\"logo\"><a href=\"/\"><img src=\"/ongo/images/f-logo.png\" alt=\"온라인 고물상\"></a></div>\n");
      out.write("            </div>\n");
      out.write("            <span>서울특별시 강남구 삼성로111길\n");
      out.write("              ⓒ TEAM Devel-Up. All Rights Reserved.</span>\n");
      out.write("            <span><em class=\"blk\">대표전화</em> : 02-000-0000</span>\n");
      out.write("            <span><em class=\"blk\">FAX</em> : 02-000-0000</span>\n");
      out.write("            <div id=\"GoTop\" class=\"gotop\">\n");
      out.write("              <button type=\"button\" class=\"btn\" onclick=\"$(window).scrollTop(0);\"><span class=\"visually-hidden\">맨위로 가기</span>\n");
      out.write("                <span><i class=\"las la-arrow-up\"></i></span>\n");
      out.write("              </button>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <!-- //Footer -->\n");
      out.write("    </section>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- // content -->\n");
      out.write(" <body>\n");
      out.write("<!-- modal -->\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"Modal\" aria-hidden=\"true\">\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("            <div class=\"modal-tit\">\n");
      out.write("                <h2 class=\"h3\">쪽지</h2>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-con\">\n");
      out.write("                <div class=\"tbl grid-layout grid1\">\n");
      out.write("                    <div class=\"grid-item\">\n");
      out.write("                    <label for=\"IUY_CLSS_NM\">수신자</label>\n");
      out.write("                    <div class=\"tbl-basic-td\">\n");
      out.write("                        <div class=\"input-wrap w100\">\n");
      out.write("                            <span id=\"IUY_CLSS_NM\">닉네임</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"grid-item\">\n");
      out.write("                        <label for=\"IUY_CLSS_CNTS\">내용적기</label>\n");
      out.write("                        <div class=\"tbl-basic-td\">\n");
      out.write("                        <div class=\"input-wrap w100\">\n");
      out.write("                            <div class=\"input-wrap w100\">\n");
      out.write("                            <textarea class=\"grid-input\" role=\"textbox\" id=\"HOFS_INTR_MTRL_CNTS\" name=\"HOFS_INTR_MTRL_CNTS\" title=\"쪽지내용 입력\" maxlength=\"500\" rows=\"5\"></textarea>\n");
      out.write("                          </div>\n");
      out.write("                        </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"btn-area\">\n");
      out.write("              <button type=\"button\" class=\"btn btn-warning text-white btn-large\"  data-bs-dismiss=\"modal\" aria-label=\"Close\">전송</button>\n");
      out.write("            </div>\n");
      out.write("            <!-- 닫기버튼 -->\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                <i class=\"las la-times\"></i>\n");
      out.write("            </button>\n");
      out.write("            <!-- //닫기버튼 -->\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	$(document).ready(function () {\n");
      out.write("		/* 홈배너 경매검색 */\n");
      out.write("		$(\"#srchWord2-btn\").on(\"click\", function () {\n");
      out.write("			location.href=\"/ongo/serarchData.do?tag=board_title&searchData=\"+$(\"#srchWord2\").val();\n");
      out.write("		})//end #srchWord2-btn event\n");
      out.write("		/* 홈배너 중고검색 */\n");
      out.write("		$(\"#srchWord1-btn\").on(\"click\", function () {\n");
      out.write("			location.href=\"/ongo/auction/serarch?searchData=\"+$(\"#srchWord1\").val();\n");
      out.write("		})//end #srchWord2-btn event\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		$.ajax({\n");
      out.write("			url : '/ongo/cooperation/ajax_list',\n");
      out.write("			type : 'get',\n");
      out.write("			success : function(data){\n");
      out.write("				var pagelist=\"\";\n");
      out.write("				for(var i=0;i<data.length;i++){\n");
      out.write("					var page = \"\";\n");
      out.write("					if(i==0){\n");
      out.write("						page = '<div class=\"carousel-item active\"><h3>'+data[i].name\n");
      out.write("					} else {\n");
      out.write("						page = '<div class=\"carousel-item\"><h3>'+data[i].name \n");
      out.write("					}\n");
      out.write("					page = page +'</h3><ul class=\"introlist\">'+\n");
      out.write("					   			 '<li><span class=\"introlist_tit\">주소</span><span class=\"introlist_txt\">'+data[i].addr+'</span></li>'+\n");
      out.write("					   			 '<li><span class=\"introlist_tit\">거래품목</span><span class=\"introlist_txt\">'+data[i].content+'</span></li>'+\n");
      out.write("					   			 '<li><span class=\"introlist_tit\">문의</span><span class=\"introlist_txt\">'+data[i].tel+'</span></li>'+\n");
      out.write("					   			 '<li><span class=\"introlist_tit\">견적</span><span class=\"introlist_txt\">'+data[i].email+'</span></li></ul>'\n");
      out.write("					if(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id!=null && user.member_role!=2}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\n");
      out.write("						page = page + '<div class=\"introlink\"><span><a href=\"/ongo/recycle/writepage?receive_id='+data[i].name+'\">거래요청</a></span></div></div>' \n");
      out.write("					} else {\n");
      out.write("						page = page + '</div>'\n");
      out.write("					}\n");
      out.write("					pagelist = pagelist + page;\n");
      out.write("				}\n");
      out.write("				document.getElementById(\"intro1slider\").childNodes[1].innerHTML = pagelist;\n");
      out.write("				itemlist = document.getElementById(\"intro1slider\").childNodes[1].childNodes\n");
      out.write("			},\n");
      out.write("			error : function(obj,msg,statusMsg){\n");
      out.write("				alert(\"오류:\"+statusMsg);\n");
      out.write("			}\n");
      out.write("		})//end ajax\n");
      out.write("		\n");
      out.write("		markerChg();\n");
      out.write("		makeMap();\n");
      out.write("		\n");
      out.write("	})//end document ready\n");
      out.write("	var itemlist;\n");
      out.write("	var activeNo = 0;\n");
      out.write("	function markerChg(){\n");
      out.write("		itemlist = document.getElementById(\"intro1slider\").childNodes[1].childNodes\n");
      out.write("		for(var i=0; i<itemlist.length; i++){\n");
      out.write("			if(itemlist[i].className==\"carousel-item active\"){\n");
      out.write("				activeNo = i;\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		makeMap();\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function makeMap(){\n");
      out.write("		var locations = [\n");
      out.write("			{place:\"소정자원\", lat:37.5135381, lng:127.0520362},\n");
      out.write("			{place:\"규민강철\", lat:37.23444, lng:127.201346},\n");
      out.write("			{place:\"태원강철\", lat:35.8460881, lng:128.6385098},\n");
      out.write("			{place:\"경민강철\", lat:35.1861875, lng:129.1226139},\n");
      out.write("			{place:\"성민자원\", lat:33.4896229, lng:126.4600159},\n");
      out.write("			{place:\"윤희자원\", lat:35.8795273, lng:127.1109433}\n");
      out.write("		]		\n");
      out.write("		\n");
      out.write("		var mapOptions = {\n");
      out.write("			    center: new naver.maps.LatLng(35.9819689, 128.094434),\n");
      out.write("			    zoom: 7\n");
      out.write("			};\n");
      out.write("\n");
      out.write("			var map = new naver.maps.Map('map', mapOptions);\n");
      out.write("		\n");
      out.write("		var marker = new naver.maps.Marker({\n");
      out.write("			map : map,\n");
      out.write("			title : locations[activeNo].place,\n");
      out.write("			position : new naver.maps.LatLng(locations[activeNo].lat,locations[activeNo].lng)\n");
      out.write("		})\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("<!-- //modal -->\n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
