/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-26 00:44:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.dealBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dealBoard_005flist3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/DevelUp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DevelUp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/DevelUp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DevelUp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1671969684817L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/ongo/common/deal/js/paginate.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"/ongo/common/deal/css/paginate.css\"> \n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".dataRow:hover {\n");
      out.write("	background: #ddd;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	var type = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("	$(document).ready(\n");
      out.write("			function() {\n");
      out.write("				$(\"#dealType\").val(type).attr(\"selected\", \"selected\");\n");
      out.write("				$(\"#dealType\").change(\n");
      out.write("						function() {\n");
      out.write("							location.href = \"/ongo/deal_listAll3.do?dealType=\"\n");
      out.write("									+ encodeURI($(this).val());\n");
      out.write("						})\n");
      out.write("			})\n");
      out.write("			\n");
      out.write("		\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<!-- 이  아래부터  content부분 부터 복사해서 붙여넣기 하시면 됩니다. 하단 footer부분 인클루트 시켜주세요 -->\n");
      out.write("\n");
      out.write("	<!-- content   -->\n");
      out.write("	<!-- title -->\n");
      out.write("	<div class=\"sub_top\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<h1>중고거래</h1>\n");
      out.write("			<span class=\"blue\">보다 더 · 당신의 일상과 가깝게</span><br/>\n");
      out.write("			<div class=\"form_box d-grid d-md-flex justify-content-md-end\" style=\"width:400px; float: left;\">\n");
      out.write("				<select class=\"form-select grid-input\" id=\"dealType\" name=\"dealType\">\n");
      out.write("					<option value=\"all\">전체</option>\n");
      out.write("					<option value=\"중고\">중고</option>\n");
      out.write("					<option value=\"나눔\">나눔</option>\n");
      out.write("				</select>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		<div class=\"container\">\n");
      out.write("\n");
      out.write("\n");
      out.write("			<div class=\"board_list\">\n");
      out.write("				<div class=\"board_info d-flex\">\n");
      out.write("					 <div class=\"total\">\n");
      out.write("					</div> \n");
      out.write("						<div class=\"form_box\">\n");
      out.write("	                        <fieldset>\n");
      out.write("	                            <legend class=\"visually-hidden\">검색</legend>\n");
      out.write("	                            <div class=\"input-group\">\n");
      out.write("	                                 <div class=\"select\">\n");
      out.write("	                                    <label class=\"visually-hidden\" for=\"category\">검색 구분</label>\n");
      out.write("	                                </div>\n");
      out.write("	                                <input type=\"search\" id=\"searchBox\" class=\"form-control\" name=\"keyword\" title=\"검색어 입력\" placeholder=\"검색어를 입력하세요.\" value=\"\">\n");
      out.write("	                                <button type=\"button\" class=\"btn btn-search\" onclick=\"#\"><i class=\"las la-search\"></i> 검색</button>\n");
      out.write("	                            </div>\n");
      out.write("	                        </fieldset>\n");
      out.write("	                    </div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		\n");
      out.write("	\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- 게시판  -->\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<table class=\"table table-borderless\" id=\"myTable\">\n");
      out.write("			<!-- table-borderless -->\n");
      out.write("			<colgroup>\n");
      out.write("\n");
      out.write("				<col width=\"10%\">\n");
      out.write("				<!-- 구분 -->\n");
      out.write("				<col width=\"20%\">\n");
      out.write("				<!-- 제품사진 -->\n");
      out.write("				<col width=\"50%\">\n");
      out.write("				<!-- 제목 -->\n");
      out.write("				<col width=\"15%\">\n");
      out.write("				<!-- 가격 -->\n");
      out.write("				<col width=\"10%\">\n");
      out.write("				<!-- 작성자 -->\n");
      out.write("				<col width=\"15%\">\n");
      out.write("				<!-- 작성일 -->\n");
      out.write("				<col width=\"8%\">\n");
      out.write("				<!-- 조회수 -->\n");
      out.write("				<col width=\"10%\">\n");
      out.write("				<!-- 거래상태 -->\n");
      out.write("			</colgroup>\n");
      out.write("			<thead>\n");
      out.write("				<tr>\n");
      out.write("					<th class=\"table-header\" scope=\"col\">구분</th>\n");
      out.write("					<th class=\"table-header\" scope=\"col\">상품 사진</th>\n");
      out.write("					<th class=\"table-header-title\" scope=\"col\">제목</th>\n");
      out.write("					<th class=\"table-header\" scope=\"col\">가격</th>\n");
      out.write("					<th class=\"table-header\" scope=\"col\">작성자</th>\n");
      out.write("					<th class=\"table-header\" scope=\"col\">작성일</th>\n");
      out.write("					<th class=\"table-header\" scope=\"col\">조회수</th>\n");
      out.write("					<th class=\"table-header\" scope=\"col\">거래상태</th>\n");
      out.write("				</tr>\n");
      out.write("			</thead>\n");
      out.write("			<tbody>\n");
      out.write("				");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("			</tbody>\n");
      out.write("		</table>\n");
      out.write("		<br/>\n");
      out.write("		<br/>\n");
      out.write("		\n");
      out.write("	<!-- 	리스트에 ajax시도하였으나 실패;\n");
      out.write("		<script type=\"text/javascript\">\n");
      out.write("			window.onload = function () {\n");
      out.write("				//alert(\"준비완료\")\n");
      out.write("				var dealIMG = {\"deal_number\":$(\"#dealIMG\").text()}\n");
      out.write("				$.ajax({\n");
      out.write("					url: \"/ongo/auction/mainlayout\",\n");
      out.write("					type: \"get\",\n");
      out.write("					data: dealIMG,\n");
      out.write("					success: function(ajaxlist) {\n");
      out.write("							mydata = \"\";\n");
      out.write("							\n");
      out.write("							if(ajaxlist != null){\n");
      out.write("								for (var i = 0; i < ajaxlist.length; i++) {\n");
      out.write("									mydata = mydata + \"<img src='/ongo/WEB-INF/dealUpload/\"+ajaxlist.storeFilename +\"'>\";\n");
      out.write("								}\n");
      out.write("							}else{\n");
      out.write("									mydata = \"<img src='/ongo/WEB-INF/static/images/myphoto.png'>\";\n");
      out.write("							}\n");
      out.write("							$(\"#dealListImg\").html(mydata); \n");
      out.write("						},\n");
      out.write("					error: function (a,b,c) {\n");
      out.write("						alert(c)\n");
      out.write("					}\n");
      out.write("				})\n");
      out.write("			}\n");
      out.write("		</script>\n");
      out.write("	 -->\n");
      out.write("              \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 		<div class=\"input-group\">\n");
      out.write("			<label for=\"searchBox\">검색 : </label> \n");
      out.write("			<input type=\"search\" id=\"searchBox\" placeholder=\"\">\n");
      out.write("		</div> -->\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<div class=\"btn-area\" >\n");
      out.write("		<button class=\"btn btn-primary btn-large\" type=\"button\"\n");
      out.write("			onclick=\"location.href='/ongo/dealRegister'\" >글쓰기</button>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("		let options = {\n");
      out.write("			numberPerPage : 5, //Cantidad de datos por pagina\n");
      out.write("			goBar : true, //Barra donde puedes digitar el numero de la pagina al que quiere ir\n");
      out.write("			pageCounter : true, //Contador de paginas, en cual estas, de cuantas paginas\n");
      out.write("		};\n");
      out.write("\n");
      out.write("		let filterOptions = {\n");
      out.write("			el : '#searchBox' //Caja de texto para filtrar, puede ser una clase o un ID\n");
      out.write("		};\n");
      out.write("\n");
      out.write("		paginate.init('#myTable', options, filterOptions);\n");
      out.write("\n");
      out.write("		var category = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("		$(document)\n");
      out.write("				.ready(\n");
      out.write("						function() {\n");
      out.write("							//alert(category)\n");
      out.write("							$(\"#category\").val(category).attr(\"selected\",\n");
      out.write("									\"selected\");\n");
      out.write("							$(\"#category\")\n");
      out.write("									.change(\n");
      out.write("											function() {\n");
      out.write("												location.href = \"/ongo/deal_listAll3.do?category=\"\n");
      out.write("														+ encodeURI($(this)\n");
      out.write("																.val());\n");
      out.write("											})\n");
      out.write("\n");
      out.write("						})\n");
      out.write("	</script>\n");
      out.write("	<!-- Footer -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\n");
      out.write("	<!-- //Footer -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/dealBoard/dealBoard_list3.jsp(129,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("board");
      // /WEB-INF/dealBoard/dealBoard_list3.jsp(129,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/dealBoard/dealBoard_list3.jsp(129,4) '${dealtotallist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dealtotallist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("					<tr onclick=\"location.href='/ongo/dealRead.do?deal_number=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.deal_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&state=READ'\" class=\"dataRow\">\n");
            out.write("						");
            out.write("\n");
            out.write("						<td><span class=\"gray-bold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.dealType }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\n");
            out.write("						<td id=\"dealListImg\"> <img alt=\"\" src=\"/ongo/dealUpload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.originalFilename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" onerror=\"this.style.display='none'\"  width=\"50\" height=\"50\"></td>\n");
            out.write("						<td><span class=\"gray-bold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\n");
            out.write("						<td><span class=\"blue-bold\">");
            if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("</span></td>\n");
            out.write("						<td><span class=\"blue-bold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.member_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\n");
            out.write("						<td><span class=\"blue-bold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.write_date }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\n");
            out.write("						<td><span class=\"blue-bold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.hits }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\n");
            out.write("						<td><span class=\"blue-bold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.product_state }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\n");
            out.write("					</tr>\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/dealBoard/dealBoard_list3.jsp(135,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.product_price}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/dealBoard/dealBoard_list3.jsp(135,34) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###원");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }
}
