/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-26 01:16:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.dealBoard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dealBoard_005fread_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/DevelUp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DevelUp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/DevelUp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DevelUp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1671969684817L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fpattern;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fpattern = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fpattern.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head> \n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("	//구분 저장공유\n");
      out.write("	$(document).ready(function(){ \n");
      out.write("		data = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.dealType}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \n");
      out.write("		$(\"#dealType\").val(data).attr(\"selected\", \"selected\"); \n");
      out.write("	});\n");
      out.write("	//상품카테고리 저장공유\n");
      out.write("	$(document).ready(function(){ \n");
      out.write("		data = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.product_category}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \n");
      out.write("		$(\"#product_category\").val(data).attr(\"selected\", \"selected\"); \n");
      out.write("	});\n");
      out.write("\n");
      out.write("	//거래요청버튼 클릭 시 \n");
      out.write("	$(document).ready(function(){ \n");
      out.write("	$(\"#dealreq-btn\").on(\"click\", function() {\n");
      out.write("		var seller_id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("		var req_id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("		var deal_number=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.deal_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("		\n");
      out.write("		 location.href=\"/ongo/history/dealreq?seller_id=\"+seller_id+\"&req_id=\"+req_id+\"&deal_number=\"+deal_number;\n");
      out.write("				 \n");
      out.write("		 })\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- 이 아래부터  content부분 복사해서 붙여넣기 하시면 됩니다. 하단 footer부분 인클루트 시켜주세요 -->\n");
      out.write("\n");
      out.write("<!-- content -->\n");
      out.write("<div id=\"contents\">\n");
      out.write("        <!-- title -->\n");
      out.write("        <div class=\"sub_top\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <h1>중고</h1>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- //title -->\n");
      out.write("\n");
      out.write("        <!-- 게시판 -->\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <form  action=\"/ongo/dealRead.do?deal_number=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.deal_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&state=UPDATE\" method=\"post\">\n");
      out.write("                <input type=\"hidden\" name=\"countPerPage\" id=\"countPerPage\" value=\"10\">\n");
      out.write("                <input type=\"hidden\" name=\"zon\" id=\"zon\" value=\"\">\n");
      out.write("\n");
      out.write("                <!-- 현재 탭 표시 -->\n");
      out.write("                <h2 class=\"visually-hidden\">중고거래</h2>\n");
      out.write("                <!-- //현재 탭 표시 -->\n");
      out.write("\n");
      out.write("		\n");
      out.write("					<!-- 로그인시스템 생성전 임시필요 -->\n");
      out.write("			<!-- 		<div class=\"cont-box-inner\">\n");
      out.write("						<div class=\"tbl grid-layout grid2\">\n");
      out.write("							<div class=\"grid-item colspan2\">\n");
      out.write("								<label for=\"HOFS_DTADR\">임시아이디(작성자)</label>\n");
      out.write("								<div class=\"tbl-basic-td\">\n");
      out.write("									<div class=\"input-wrap w20\">\n");
      out.write("										<input class=\"grid-input\" type=\"text\" maxlength=\"50\"\n");
      out.write("											title=\"id\" id=\"id\" name=\"id\">\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							</div>\n");
      out.write("					</div> -->\n");
      out.write("							\n");
      out.write("				\n");
      out.write("							\n");
      out.write("							<div class=\"cont-box-inner\">\n");
      out.write("					<div class=\"tbl grid-layout grid2\">\n");
      out.write("						<div class=\"grid-item colspan2\">\n");
      out.write("							<label for=\"select_target_1\">구분</label>\n");
      out.write("							<div class=\"tbl-basic-td\">\n");
      out.write("								<div class=\"input-wrap w20\">\n");
      out.write("									<select class=\"form-select grid-input\" id=\"dealType\" name=\"dealType\" >\n");
      out.write("										<option value=\"중고\">중고</option>\n");
      out.write("										<option value=\"나눔\">나눔</option>\n");
      out.write("									</select>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("							\n");
      out.write("							\n");
      out.write("							\n");
      out.write("							\n");
      out.write("							\n");
      out.write("							\n");
      out.write("							<div class=\"grid-item colspan2\">\n");
      out.write("								<label for=\"select_target_1\" >상품카테고리</label>\n");
      out.write("								<div class=\"tbl-basic-td\">\n");
      out.write("									<div class=\"input-wrap w20\">\n");
      out.write("									\n");
      out.write("										<select class=\"form-select grid-input\" title=\"게시판\" id=\"product_category\" name=\"product_category\">\n");
      out.write("											<option value=\"디지털&가전\">디지털&가전</option>\n");
      out.write("											<option value=\"가구&인테리어\">가구&인테리어</option>\n");
      out.write("											<option value=\"유아동\">유아동</option>\n");
      out.write("											<option value=\"생활&가공식품\">생활&가공식품</option>\n");
      out.write("											<option value=\"레져&스포츠\">레져&스포츠</option>\n");
      out.write("											<option value=\"여성잡화\">여성잡화</option>\n");
      out.write("											<option value=\"여성의류\">여성의류</option>\n");
      out.write("											<option value=\"남성잡화\">남성잡화</option>\n");
      out.write("											<option value=\"남성의류\">남성의류</option>\n");
      out.write("											<option value=\"게임&취미\">게임&취미</option>\n");
      out.write("											<option value=\"뷰티&미용\">뷰티&미용</option>\n");
      out.write("											<option value=\"반려동물용품\">반려동물용품</option>\n");
      out.write("											<option value=\"도서&티켓&음반\">도서&티켓&음반</option>\n");
      out.write("											<option value=\"기타\">기타</option>\n");
      out.write("										</select>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("							<div class=\"grid-item colspan2\">\n");
      out.write("								<label for=\"HOFS_DTADR\">제목</label>\n");
      out.write("								<div class=\"tbl-basic-td\">\n");
      out.write("									<div class=\"input-wrap w100\">\n");
      out.write("										");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.board_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						\n");
      out.write("							\n");
      out.write("							<div class=\"grid-item colspan2\">\n");
      out.write("								<label for=\"HOFS_DTADR\">작성자</label>\n");
      out.write("								<div class=\"tbl-basic-td\" onclick=\"modalData(this)\">\n");
      out.write("									<div class=\"col-md-8\" >\n");
      out.write("									");
      out.write("\n");
      out.write("										<a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" >\n");
      out.write("									          ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("									        </a>\n");
      out.write("									        <ul class=\"dropdown-menu\" style=\"width: 100px;\">\n");
      out.write("									            <li><a class=\"dropdown-item\" href=\"#\" title=\"쪽지보내기 팝업\" data-bs-toggle=\"modal\" data-bs-target=\"#sendNoteModal\" id=sendnote>쪽지보내기</a></li>\n");
      out.write("									            <li><a class=\"dropdown-item\" href=\"#\" title=\"회원정보 팝업\" data-bs-toggle=\"modal\" data-bs-target=\"#userInfoModal\" id=userinfo>회원정보보기</a></li>\n");
      out.write("									            <li><a class=\"dropdown-item\" href=\"#\">거래내역보기</a></li>\n");
      out.write("									        </ul>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							\n");
      out.write("							<div class=\"grid-item colspan2\">\n");
      out.write("								<label for=\"HOFS_DTADR\">금액</label>\n");
      out.write("								<div class=\"tbl-basic-td\">\n");
      out.write("									<div class=\"input-wrap w30 me-4\">\n");
      out.write("									\n");
      out.write("									\n");
      out.write("									<span class=\"blue-bold\">");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write("</span>\n");
      out.write("										<!-- <input class=\"grid-input\" type=\"number\" maxlength=\"50\"\n");
      out.write("											title=\"product_price\" id=\"product_price\" name=\"product_price\"> -->\n");
      out.write("									</div>\n");
      out.write("									<!--<div class=\"form-check\">\n");
      out.write("										<input type=\"checkbox\" class=\"form-check-input\" value=\" \">\n");
      out.write("										<label class=\"form-check-label\"> <span class=\"radio\"></span>나눔</label> \n");
      out.write("									</div>-->\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("							<div class=\"grid-item colspan2\">\n");
      out.write("								<label for=\"HOFS_DTADR\">내용</label>\n");
      out.write("								<div class=\"tbl-basic-td\">\n");
      out.write("									<div class=\"input-wrap w100\">\n");
      out.write("										");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.board_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						\n");
      out.write("					\n");
      out.write("								\n");
      out.write("							\n");
      out.write("							\n");
      out.write("\n");
      out.write("								<div class=\"grid-item colspan2\">\n");
      out.write("								<label for=\"HOFS_DTADR\">사진</label>\n");
      out.write("								<div class=\"tbl-basic-td\">\n");
      out.write("									<div class=\"input-wrap w100\">\n");
      out.write("										");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								</div>\n");
      out.write("							\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("							<div class=\"grid-item colspan2\">\n");
      out.write("								<label for=\"HOFS_DTADR\">첨부파일</label>\n");
      out.write("								<div class=\"tbl-basic-td\">\n");
      out.write("									<div class=\"input-wrap w100\">\n");
      out.write("										");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("									\n");
      out.write("										\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div> \n");
      out.write("\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				\n");
      out.write("				\n");
      out.write("				\n");
      out.write("					\n");
      out.write("							\n");
      out.write("							\n");
      out.write("							\n");
      out.write("							\n");
      out.write("					\n");
      out.write("					<!-- <div class=\"btn-area\">\n");
      out.write("						<input type=\"submit\" value=\"게시글 등록\" class=\"btn btn-primary btn-large\" />\n");
      out.write("					</div> -->\n");
      out.write("			<div class=\"btn-area\">\n");
      out.write("\n");
      out.write("				<button class=\"btn btn-primary btn-large\" type=\"button\" onclick=\"location.href='/ongo/deal_listAll2.do?dealType=all'\">리스트</button>\n");
      out.write("				<button class=\"btn btn-primary btn-large\" id=\"dealreq-btn\" type=\"button\" >거래요청</button>\n");
      out.write("											<!-- onclick=\"location.href='/ongo/history/dealreq?\n");
      out.write("				seller_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&req_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&deal_number=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.deal_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" -->										\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("		");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("	\n");
      out.write("		</form>\n");
      out.write("		\n");
      out.write("						\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("	<!-- send note modal -->\n");
      out.write("	<div class=\"modal fade\" id=\"sendNoteModal\" tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"Modal\" aria-hidden=\"true\">\n");
      out.write("		<form action=\"/ongo/mypage/note/sendnote\" method=\"post\">\n");
      out.write("			<div class=\"modal-dialog\">\n");
      out.write("				<div class=\"modal-content\">\n");
      out.write("					<div class=\"modal-body\">\n");
      out.write("						<div class=\"modal-tit\">\n");
      out.write("							<h2 class=\"h3\">쪽지</h2>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"modal-con\">\n");
      out.write("							<div class=\"tbl grid-layout grid1\">\n");
      out.write("								<div class=\"grid-item\">\n");
      out.write("									<label for=\"IUY_CLSS_NM\">수신자</label>\n");
      out.write("									<div class=\"tbl-basic-td\">\n");
      out.write("										<div class=\"input-wrap w100\">\n");
      out.write("											<span><textarea class=\"grid-input\" role=\"textbox\" id=\"reply_receive_id\" name=\"receive_id\" title=\"수신자\" maxlength=\"500\" rows=\"1\" readonly=\"readonly\" required=\"required\"></textarea></span>\n");
      out.write("											<input type=\"text\" hidden=\"true\" id=\"send_id\" name=\"send_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("								<div class=\"grid-item\">\n");
      out.write("									<label for=\"IUY_CLSS_CNTS\">내용적기</label>\n");
      out.write("									<div class=\"tbl-basic-td\">\n");
      out.write("										<div class=\"input-wrap w100\">\n");
      out.write("											<div class=\"input-wrap w100\">\n");
      out.write("												<textarea class=\"grid-input\" role=\"textbox\"\n");
      out.write("													id=\"content\" name=\"content\"\n");
      out.write("													title=\"쪽지내용 입력\" maxlength=\"500\" rows=\"5\" required=\"required\"></textarea>\n");
      out.write("											</div>\n");
      out.write("										</div>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("						<div class=\"btn-area\">\n");
      out.write("							<button type=\"submit\" class=\"btn btn-warning text-white btn-large\"\n");
      out.write("								data-bs-dismiss=\"modal\" aria-label=\"Close\" onclick=\"sendNote()\">전송</button>\n");
      out.write("						</div>\n");
      out.write("						<!-- 닫기버튼 -->\n");
      out.write("						<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("							aria-label=\"Close\">\n");
      out.write("							<i class=\"las la-times\"></i>\n");
      out.write("						</button>\n");
      out.write("						<!-- //닫기버튼 -->\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</form>\n");
      out.write("	</div>\n");
      out.write("	<!-- //send note modal -->\n");
      out.write("\n");
      out.write("	<!-- user info modal -->\n");
      out.write("	<div class=\"modal fade\" id=\"userInfoModal\" tabindex=\"-1\"\n");
      out.write("		aria-labelledby=\"Modal\" aria-hidden=\"true\">\n");
      out.write("		<div class=\"modal-dialog\">\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<div class=\"modal-body\">\n");
      out.write("					<div class=\"modal-tit\">\n");
      out.write("						<h2 class=\"h3\">회원정보</h2>\n");
      out.write("					</div>\n");
      out.write("					<div class=\"modal-con\">\n");
      out.write("						<div class=\"tbl grid-layout grid1\">\n");
      out.write("							<div class=\"grid-item\">\n");
      out.write("								<label for=\"IUY_CLSS_NM\">ID</label>\n");
      out.write("								<div class=\"tbl-basic-td\">\n");
      out.write("									<div class=\"input-wrap w100\">\n");
      out.write("										<span id=\"member_id\"></span>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"grid-item\">\n");
      out.write("								<label for=\"IUY_CLSS_CNTS\">E-mail</label>\n");
      out.write("								<div class=\"tbl-basic-td\">\n");
      out.write("									<div class=\"input-wrap w100\">\n");
      out.write("										<span id=\"member_email\"></span>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("							<div class=\"grid-item\">\n");
      out.write("								<label for=\"IUY_CLSS_CNTS\">가입날짜</label>\n");
      out.write("								<div class=\"tbl-basic-td\">\n");
      out.write("									<div class=\"input-wrap w100\">\n");
      out.write("										<span id=\"member_date\"></span>\n");
      out.write("									</div>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<!-- 닫기버튼 -->\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"\n");
      out.write("						aria-label=\"Close\">\n");
      out.write("						<i class=\"las la-times\"></i>\n");
      out.write("					</button>\n");
      out.write("					<!-- //닫기버튼 -->\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<!-- //user info modal -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Footer -->\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/footer.jsp", out, false);
      out.write("\n");
      out.write("<!-- //Footer -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	//prepare data when popup menu on ID\n");
      out.write("	function modalData(clicked_element){\n");
      out.write("		//get and set to data for note\n");
      out.write("		var row_a = clicked_element.getElementsByTagName(\"a\");\n");
      out.write("		var receive_id = (row_a[0].textContent).trim();\n");
      out.write("		var id = {\"member_id\":receive_id};\n");
      out.write("		$(\"#reply_receive_id\").html(receive_id);\n");
      out.write("		\n");
      out.write("		$.ajax({\n");
      out.write("			url : \"/ongo/member/ajax_memberread\",\n");
      out.write("			type : \"get\",\n");
      out.write("			data : id,\n");
      out.write("			success : function(data){\n");
      out.write("				//data transfer to user info in modal\n");
      out.write("				$(\"#member_id\").html(data.member_id);\n");
      out.write("				$(\"#member_email\").html(data.member_email);\n");
      out.write("				$(\"#member_date\").html(data.member_date);\n");
      out.write("			},\n");
      out.write("			error : function(obj,msg,statusMsg){\n");
      out.write("				alert(\"오류발생:\"+statusMsg);\n");
      out.write("			}//end error\n");
      out.write("		})//end ajax\n");
      out.write("	}//end modalData\n");
      out.write("	\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fpattern.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /WEB-INF/dealBoard/dealBoard_read.jsp(159,33) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("#,###원");
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_eval_fmt_005fformatNumber_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_fmt_005fformatNumber_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_fmt_005fformatNumber_005f0);
        }
        do {
          out.write("\n");
          out.write("										");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.product_price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          int evalDoAfterBody = _jspx_th_fmt_005fformatNumber_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_fmt_005fformatNumber_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fpattern.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/dealBoard/dealBoard_read.jsp(191,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("file");
      // /WEB-INF/dealBoard/dealBoard_read.jsp(191,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/dealBoard/dealBoard_read.jsp(191,10) '${filedtolist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${filedtolist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("											<img alt=\"\" src=\"/ongo/dealUpload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.originalFilename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"width: 500px;\">\n");
            out.write("										");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/dealBoard/dealBoard_read.jsp(206,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("file");
      // /WEB-INF/dealBoard/dealBoard_read.jsp(206,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/dealBoard/dealBoard_read.jsp(206,10) '${filedtolist}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${filedtolist}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("											<label for=\"HOFS_DTADR\"><a href=\"/ongo/dealDownload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dealRead.deal_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('/');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.dealFile_number}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.originalFilename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></label><br/>\n");
            out.write("										");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');
          out.write('	');
          out.write('	');
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("	\n");
          out.write("			");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("				\n");
          out.write("				\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/dealBoard/dealBoard_read.jsp(239,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.member_id==dealRead.member_id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<div class=\"btn-area\">\n");
          out.write("				<button type=\"submit\" class=\"btn btn-success btn-large\">수정</button>\n");
          out.write("			</div>\n");
          out.write("			\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
